// King Krook stops slipping and sliding.
// ============================================================================
// Per user: "King krook still moves in a slip and sliding manner. He needs to move more normally, fix it".
//
// 1. THE WALK LURCH. His walk art barely strides (short legs under the belly, the cape hem on the floor), but its
//    nine frames were not drawn on one registration: the whole figure sits at a different x in each. Measured on
//    the belly plate (scripts/gen_krook_walk_reg.mjs), the body wanders across 14% of the frame - forward in frames
//    3-4, back in 5-6, about 45 px on screen - while his idle frames hold it within 0.2%. Drawn at a steady world
//    position, that is a body lurching back and forth over the floor every stride: the slip-and-slide. Each walk
//    frame is now shifted so the belly sits where it does in the idle set (_KROOK_WALK_REG, fractions of the frame
//    width, + toward his snout, applied after the facing mirror so it turns with him). The body now travels at his
//    real speed, legs, tail and cape animating around it, and starting or stopping a walk no longer jumps.
// 2. THE CLAW GLIDE. The claw swipe set vx = 4 for its whole 700 ms, so the swipe pose skated ~170 px across the
//    floor. It is now a step into the swipe - 4 easing to 0 over the first 300 ms (~36 px) - and he is planted for
//    the strike at 350 ms. The swipe's hitbox, damage and timing are unchanged.
//
// Guarded + atomic + idempotent. EOL-aware.
import { readFileSync, writeFileSync, renameSync, statSync } from 'node:fs';
const F = process.env.LX_GAME_FILE || 'C:/Users/dpeh0/Mojiworld/mojiworld_game.html';
let s = readFileSync(F, 'utf8');
const n0 = s.length;
if (/v0\.30\.(x|\d+) krook-walk/.test(s)) { console.log('already applied'); process.exit(0); }
const crlf = (s.match(/\r\n/g) || []).length, lf = (s.match(/\n/g) || []).length;
const EOL = crlf > lf / 2 ? '\r\n' : '\n';
const die = (m) => { console.error('ABORT ' + m); process.exit(1); };
const count = (a) => s.split(a).length - 1;
const once = (label, a, z) => { if (count(a) !== 1) die(label + ' matched ' + count(a)); s = s.replace(a, () => z); };
const L = (...x) => x.join(EOL);
const REG = [-0.0002, 0.0005, -0.0247, -0.0638, -0.0639, 0.0756, 0.0751, -0.0245, -0.0005];   // gen_krook_walk_reg.mjs

// 1a. the table, beside the walk weights
once('table', 'const _BOSS_WALK_WSUM = Object.create(null);', L(
  '// v0.30.1038 krook-walk — King Krook\'s walk frames on ONE registration (per user: "King krook still moves in a slip and',
  '// sliding manner. He needs to move more normally"). The frames place his body at a different x each - the belly',
  '// wanders 14% of the frame, ~45 px on screen, against 0.2% in his idle set - so a steady walk drew a body lurching',
  '// back and forth over the floor every stride. Each walk frame is shifted by this fraction of its width (+ toward',
  '// his snout; _drawBossSprite applies it after the facing mirror) so the belly sits where the idle set holds it.',
  '// Generated by scripts/gen_krook_walk_reg.mjs; --check fails if the art drifts.',
  'const _KROOK_WALK_REG = ' + JSON.stringify(REG) + ';',
  '// ...and the whole walk set sits 15 px further forward on screen than his idle set (the two sets reach the draw',
  '// through different content boxes), so starting or stopping a walk nudged him. This trim, a fraction of the draw',
  '// width before the calibration scale, measured in his arena by scripts/krook_walk_test.mjs, puts the walking body',
  '// where the idle one stands.',
  'const _KROOK_WALK_TRIM = -0.0371;',
  'const _BOSS_WALK_WSUM = Object.create(null);'));

// 1b. applied where the frame is drawn, after the calib transform (inside the facing mirror)
once('draw', L(
  '    m._visW = targetW * _bc.s; m._visH = targetH * _bc.s;',
  '  }',
  '  _lxUseEntityImageQuality(ctx);'), L(
  '    m._visW = targetW * _bc.s; m._visH = targetH * _bc.s;',
  '  }',
  '  // v0.30.1038 krook-walk — hold King Krook\'s body still inside his walk frames (see _KROOK_WALK_REG)',
  "  if (m.type === 'kingKrook' && _animated && sprite && sprite._lxFi != null && BOSS_WALK_FRAMES.kingKrook && BOSS_WALK_FRAMES.kingKrook[sprite._lxFi] === sprite && _KROOK_WALK_REG[sprite._lxFi] != null) ctx.translate((_KROOK_WALK_REG[sprite._lxFi] + _KROOK_WALK_TRIM) * targetW, 0);",
  '  _lxUseEntityImageQuality(ctx);'));

// 2. the claw lunge
once('claw', '      m.vx = m.facing * 4;     // lunge',
  '      m.vx = t < 300 ? m.facing * 4 * (1 - t / 300) : 0;     // v0.30.1038 krook-walk — a step into the swipe, then planted (was 4 for all 700 ms: the swipe pose skated ~170 px)');

if (!s.includes('function _drawBossSprite(sprite, m, sx, sy, _isAttack, _animated)')) die('_drawBossSprite signature moved');
const grew = s.length - n0;
if (grew < 900 || grew > 3000) die('size moved ' + grew);
writeFileSync(F + '.tmp', s, 'utf8');
if (statSync(F + '.tmp').size < 5000000) die('tmp small');
{
  let done = false, lastErr = null;
  for (let a = 1; a <= 8 && !done; a++) {
    try { renameSync(F + '.tmp', F); done = true; }
    catch (e) { lastErr = e; if (e.code !== 'EPERM' && e.code !== 'EBUSY') throw e; Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 1500 * a); }
  }
  if (!done) die('rename kept failing: ' + lastErr.code);
}
console.log('applied: krook-walk (+' + grew + ' chars)');
