// Live test: ARIEL'S EMBER MOTES draw a sprite instead of a flat orange disc.
//
// Per user, from a screenshot of the Ariel fight: "There are these red circles
// generated by ariel, use ludo.ai to generate specific small blazing ball
// sprite for it."
//
// The load-bearing check spies on drawImage through the real drawProjectiles,
// because the whole bug was that the enemy draw side had no route to a sprite
// for this projectile and silently fell back to ctx.arc.
//   node scripts/aries_ember_test.mjs [port]
import { chromium } from 'playwright-core';
import { existsSync } from 'node:fs';
const EXE = ['C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
const results = []; const ok = (n, c, x) => results.push({ n, pass: !!c, x });

const net_ = await import('node:net');
const free = (p) => new Promise((r) => { const s = net_.createServer();
  s.once('error', () => r(false)); s.once('listening', () => s.close(() => r(true))); s.listen(p, '127.0.0.1'); });
let PORT = process.argv[2];
for (let p = 8767; p <= 8999 && !PORT; p++) if (await free(p)) PORT = String(p);
const { spawn } = await import('node:child_process');
const srv = spawn(process.execPath, ['serve.js', PORT], { stdio: 'ignore' });
await new Promise(r => setTimeout(r, 2000));
const b = await chromium.launch({ executablePath: EXE, headless: true, args: ['--no-sandbox', '--mute-audio'] });
const page = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
const errs = []; page.on('pageerror', e => errs.push(String(e).slice(0, 160)));
await page.goto(`http://localhost:${PORT}/mojiworld_game.html`, { waitUntil: 'domcontentloaded', timeout: 180000 });
await page.waitForFunction(() => typeof LX_MOB_PROJ !== 'undefined' && typeof drawProjectiles === 'function'
  && typeof ZODIAC_AI !== 'undefined', null, { timeout: 120000 });
await page.evaluate(() => { try { void LX_MOB_PROJ.fire; } catch (e) {} });
await page.waitForFunction(() => { try { const i = LX_MOB_PROJ.fire;
  return !!(i && i.complete && i.naturalWidth > 0); } catch (e) { return false; } }, null, { timeout: 40000 }).catch(() => {});
await page.waitForTimeout(2000);

const r = await page.evaluate(async () => {
  const out = {};
  const im = LX_MOB_PROJ.fire;
  out.art = { registered: !!im, ready: !!(im && im.complete && im.naturalWidth > 0),
              src: im ? im.src.split('/').pop() : '' };
  out.blit = LX_MOB_PROJ.fire && _PROJ_SPRITE_BLIT.fire ? { ..._PROJ_SPRITE_BLIT.fire } : null;

  // the enemy branch is the only one that can reach this art; prove the player
  // side is untouched by checking its own fire sprite is still the fireball
  out.playerFire = (_LX_PROJ_FOR_SKILL.fire && _LX_PROJ_FOR_SKILL.fire.src || '').split('/').pop();

  // ---- what reaches the canvas, through the real draw ----
  const proto = CanvasRenderingContext2D.prototype;
  const realDraw = proto.drawImage, realArc = proto.arc;
  let drawn = [], arcs = 0;
  proto.drawImage = function (img, ...rest) {
    try { if (img && img.src) drawn.push(img.src.split('/').slice(-2).join('/')); } catch (e) {}
    return realDraw.apply(this, [img, ...rest]);
  };
  proto.arc = function (...a) { arcs++; return realArc.apply(this, a); };
  const shoot = (owner, skill) => {
    game.projectiles = [{ x: player.x + 70, y: player.y, vx: -4, vy: 0, w: 14, h: 14, life: 80,
      damage: 1, owner, skill, color: '#ff6622', noGravity: true }];
    drawn = []; arcs = 0;
    try { drawProjectiles(); } catch (e) { out.threw = String(e).slice(0, 120); }
    return { drawn: drawn.slice(0, 3), arcs };
  };
  out.enemyFire = shoot('enemy', 'fire');
  out.playerFireDraw = shoot('player', 'fire');
  proto.drawImage = realDraw; proto.arc = realArc;
  game.projectiles = [];

  // ---- and that Ariel really is the one spawning them ----
  out.ariesSpawns = (typeof ZODIAC_AI.aries === 'function');
  out.ariesSkillInSource = true;   // asserted from the file side below
  return out;
});

// the spawn sites, read from the shipped file rather than trusted
const { readFileSync } = await import('node:fs');
const src = readFileSync('mojiworld_game.html', 'utf8');
const enemyFireSpawns = (src.match(/owner: 'enemy', skill: 'fire'/g) || []).length;

ok('the ember sprite is registered for the enemy fire key and decoded',
  r.art.registered && r.art.ready && /m_ariesember/.test(r.art.src), r.art);
ok('it draws as a tumbling ball sized close to its hitbox',
  r.blit && r.blit.mode === 'spin' && r.blit.size === 1.6 && r.blit.spinRate > 0, r.blit);
ok('an enemy fire mote now blits the SPRITE instead of falling back to a disc',
  r.enemyFire.drawn.some(s => /m_ariesember\.webp$/.test(s)),
  { drawn: r.enemyFire.drawn, arcs: r.enemyFire.arcs, threw: r.threw });
ok('the PLAYER fireball is untouched — different art, different branch',
  r.playerFire === 'p_fireball.webp'
  && r.playerFireDraw.drawn.some(s => /p_fireball\.webp$/.test(s))
  && !r.playerFireDraw.drawn.some(s => /m_ariesember/.test(s)),
  { playerSprite: r.playerFire, drew: r.playerFireDraw.drawn });
ok('Ariel is still the only enemy spawning this key (2 spawn sites, both hers)',
  enemyFireSpawns === 2, { enemyFireSpawnSites: enemyFireSpawns });
ok('no page errors', errs.length === 0, errs.slice(0, 3));

for (const q of results) console.log((q.pass ? 'PASS ' : 'FAIL ') + ' ' + q.n + '  ' + JSON.stringify(q.x ?? ''));
console.log(`${results.filter(q => q.pass).length}/${results.length} checks passed`);
await b.close(); srv.kill();
process.exit(results.every(q => q.pass) ? 0 : 1);
