// The character-creation preview stage, pop punk (final polish). Per user, three passes: "Remake the background behind the
// character, it can be more pop and punk style, do not use polkadots" (cs-stage); "less intense background, add a shadow
// rim at the bottom, remove the yellow black strips" (cs-stage2); "The floor can be better improved, the lightning sign can
// be removed, replace it with another star ... make it a AAA Pop punk style" (cs-stage3). The stage is now one illustration,
// Sprites/ui/cs/stage_pop.svg, generated by scripts/gen_cs_stage_svg.cjs. cs-stage4 (per user: "improving the stage background
// especially the backdrop") gave it a punk gig wall; cs-stage5 ("reduce the graffiti at the back, make it look like a stage,
// i like the speakers, make it slightly comic style, not so cluttered") swaps the wall for tied-back drapes and a valance. Checks the box paints it (and it loads), the
// SVG itself (two stars, no bolt, a podium floor, a bottom shadow rim, no tape, no dots), and that the old layers are off.
//   node scripts/cs_stage_pop_test.mjs [page.html] [port]    (MOJI_GAME_FILE / this repo's game by default)
import { createRequire } from 'node:module';
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const { chromium } = require('playwright-core');
const PAGE = process.argv[2] || process.env.MOJI_GAME_FILE || 'mojiworld_game.html', PORT = +(process.argv[3] || 9941);
const SVG = 'Sprites/ui/cs/stage_pop.svg';
let fails = 0; const ok = (n, c, x) => { if (!c) fails++; console.log(`${c ? 'PASS' : 'FAIL'}  ${n}  ${JSON.stringify(x === undefined ? null : x).slice(0, 220)}`); };

// the illustration itself
const svgPath = path.join(ROOT, SVG);
const svg = fs.existsSync(svgPath) ? fs.readFileSync(svgPath, 'utf8') : '';
ok('the stage illustration exists', svg.length > 2000, svg.length);
ok('it is the generator\'s output', svg.includes('final-polish cs-stage3') && fs.existsSync(path.join(ROOT, 'scripts', 'gen_cs_stage_svg.cjs')));
const starShapes = (svg.match(/<path d="M[^"]*Z" fill="#(ffe07a|f07aa8)"/g) || []).length;
ok('two stickered stars (butter and berry) and no lightning bolt', starShapes === 2 && !/M26 3 7 31h11/.test(svg) && !svg.includes('#ffe07a" stroke="#0d0a14" stroke-width="3"'), { starShapes });
ok('a podium floor: glossy top, lit rim, contact shadow', /id="top"/.test(svg) && /id="rim"/.test(svg) && /id="pool"/.test(svg) && /clip-path="url\(#faceClip\)"/.test(svg));
ok('a shadow rim at the bottom and an edge vignette', /id="bottom"/.test(svg) && /fill="url\(#bottom\)"/.test(svg) && /fill="url\(#vig\)"/.test(svg));
const smallEll = (svg.match(/<ellipse[^>]*>/g) || []).filter((e) => { const m = / rx="([0-9.]+)"/.exec(e); return m && +m[1] < 8; }).length;
ok('no dots: no <circle>, no <pattern>, no small ellipses', !/<circle/.test(svg) && !/<pattern/.test(svg) && smallEll === 0, { smallEll });
ok('the backdrop is a stage: berry drapes and a valance, the two speakers kept', svg.includes('id="drape"') && (svg.match(/fill="url\(#drape\)"/g) || []).length === 3 && svg.includes('stroke="#e8c86a" stroke-width="3"') && (svg.match(/stroke="#3b2e4f"/g) || []).length === 2);
// cs-stage6 (per user: "The back stage can look more muted, the ground can look more pronounced, make the image flow")
ok('a muted backstage: dusty burst and drapes, not the berry of the earlier passes', svg.includes('stop-color="#8e5c80"') && svg.includes('stop-color="#9a4c78"') && !svg.includes('#b0457f') && !svg.includes('#b03c74'));
ok('a pronounced floor: starts at the horizon (y 300), boards to a vanishing point, a lit edge, a light pool', svg.includes('<rect y="300" width="400" height="100" fill="url(#floor)"/>') && (svg.match(/<path d="M200,120L/g) || []).length >= 20 && svg.includes('clip-path="url(#floorClip)"') && svg.includes('fill="url(#floorPool)"'));
// cs-stage7 (per user: "the podium especially the shadow on the podium looks weird, please rectify, push the character
// vertically up slightly")
ok('the podium has soft shadows - no hard offset block under the drum, a soft contact shadow under the feet', !svg.includes('transform="translate(6 8)"') && svg.includes('fill="url(#podShadow)"') && svg.includes('fill="url(#contact)"') && svg.includes('<ellipse cx="200" cy="330" rx="122" ry="22" fill="url(#top)"'));
// cs-stage8 (per user, on a crop of the feet: "add a suitable sized shadow ellipse to make it look realistic")
const core = /<ellipse cx="([0-9.]+)" cy="([0-9.]+)" rx="([0-9.]+)" ry="([0-9.]+)" fill="url\(#contactCore\)"/.exec(svg);
ok('a realistic contact shadow: a dark core under the soles, wider than the feet (x 175-222, soles at y 332.6)', !!core && Math.abs(+core[1] - 198.5) < 2 && +core[2] >= 332 && +core[2] <= 337 && +core[1] - +core[3] < 170 && +core[1] + +core[3] > 228 && svg.includes('fill="url(#contact)"'), core && core.slice(1));
ok('not cluttered: no posters, graffiti or brickwork, two sparkles', !svg.includes('clipPath id="pc') && !svg.includes('stroke-width="9"') && !svg.includes('wallm') && (svg.match(/d="M0,-12L2\.6,-2\.6/g) || []).length === 2);
ok('no caution tape stripes', !/repeating-linear|#ffe07a" fill-opacity/.test(svg));

const server = spawn(process.execPath, [path.join(ROOT, 'serve.js'), String(PORT)], { stdio: 'ignore', cwd: ROOT });
await new Promise((r) => setTimeout(r, 1500));
const browser = await chromium.launch({ ...(process.env.PW_EXE ? { executablePath: process.env.PW_EXE } : { channel: 'msedge' }), headless: true, args: ['--mute-audio'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; page.on('pageerror', (e) => errs.push(String(e.message).slice(0, 160)));
await page.addInitScript(() => { try { localStorage.setItem('mojiworld_prologue_seen', '1'); } catch (e) {} });
await page.goto(`http://localhost:${PORT}/${PAGE}`, { waitUntil: 'domcontentloaded', timeout: 180000 });
await page.waitForFunction(() => typeof openClassSelect === 'function' && typeof player !== 'undefined', null, { timeout: 180000 });
await page.waitForTimeout(2500);
await page.evaluate(() => { const o = document.getElementById('loading-overlay'); if (o) o.style.display = 'none'; openClassSelect(); });
await page.waitForTimeout(1800);
const r = await page.evaluate(() => {
  const w = document.querySelector('#class-select-modal .cs-look-preview-wrap');
  const cs = getComputedStyle(w), be = getComputedStyle(w, '::before'), af = getComputedStyle(w, '::after');
  const vis = (q) => { const e = w.querySelector(q); return !!e && getComputedStyle(e).display !== 'none'; };
  return { bg: cs.backgroundImage, beforeContent: be.content, afterContent: af.content, ring: vis('.cs-stage-ring'), twinkle: vis('.cs-twinkle'),
    canvasFilter: getComputedStyle(document.getElementById('cs-look-canvas')).filter, canvasTranslate: getComputedStyle(document.getElementById('cs-look-canvas')).translate };
});
// the URL the box actually paints, loaded the way the browser would
const loaded = await page.evaluate(async (bg) => { const u = bg.includes('url("') ? bg.split('url("')[1].split('")')[0] : null; if (!u) return { url: null };
  const im = new Image(); im.src = u; try { await im.decode(); } catch (e) { return { url: u, ok: false }; } return { url: u, ok: im.naturalWidth > 0 }; }, r.bg);
await browser.close(); server.kill();
ok('the box paints the illustration, and nothing else on top', /stage_pop\.svg/.test(r.bg) && (r.bg.match(/url\(|gradient\(/g) || []).length === 1, r.bg.slice(0, 120));
ok('the illustration loads', loaded.ok === true && /stage_pop.svg/.test(loaded.url || ''), loaded);
ok('the old pseudos are off (no prism, tape or glow layers)', r.beforeContent === 'none' && r.afterContent === 'none', { before: r.beforeContent, after: r.afterContent });
ok('the old ring and twinkles are off', !r.ring && !r.twinkle, { ring: r.ring, twinkle: r.twinkle });
ok('the figure wears a white sticker edge', /drop-shadow\(rgb\(255, 255, 255\)/.test(r.canvasFilter), r.canvasFilter);
ok('no hard ink drop on the figure (it read as a dark twin of the legs on the podium)', !/drop-shadow\(rgba\(13, 10, 20/.test(r.canvasFilter), r.canvasFilter);
ok('the figure stands 5% higher (a share of its own height, so the phone box moves alike)', r.canvasTranslate === '0px -5%', r.canvasTranslate);
ok('no page errors', errs.length === 0, errs.slice(0, 2));
console.log(fails ? `FAIL(${fails})` : 'ALL PASS');
process.exit(fails ? 1 : 0);
