// Bake which optional boss/zodiac sprites actually exist, so the loaders stop
// probing for files that were never authored.
//
// The loaders cannot know a file is absent without asking for it: the base
// attack pose is tried as <type>.webp, and every frame set is requested as
// _0.._8 regardless of how many frames exist. On a cold boot that is a fixed
// set of guaranteed 404s — harmless but real round-trips, and console noise
// that hides genuine misses.
//
//   node scripts/gen_boss_sprite_index.mjs           # write data/boss_sprite_index.js
//   node scripts/gen_boss_sprite_index.mjs --check   # exit 1 if the baked file is stale
//
// Re-run after dropping new boss art. --check is the drift guard.
import { readFileSync, writeFileSync, renameSync, existsSync, readdirSync } from 'node:fs';

const GAME = 'mojiworld_game.html';
const OUT = 'data/boss_sprite_index.js';
const MAX = 9;                       // _BOSS_ANIM_MAX in the game
const CHECK = process.argv.includes('--check');

const src = readFileSync(GAME, 'utf8');
const listOf = (name) => {
  const m = src.match(new RegExp('const ' + name + '\\s*=\\s*\\[([\\s\\S]*?)\\];'));
  if (!m) throw new Error(name + ' not found in ' + GAME);
  return [...m[1].matchAll(/'([A-Za-z0-9_]+)'/g)].map(x => x[1]);
};
const BOSS = listOf('BOSS_SPRITE_TYPES');
const ZODIAC = listOf('ZODIAC_SPRITE_TYPES');

const filesIn = (dir) => new Set(existsSync(dir) ? readdirSync(dir) : []);

// --- base attack pose (single static frame), boss types only ---------------
const attackFiles = filesIn('Sprites/bosses/attack');
const attackBase = {};
for (const t of BOSS) {
  for (const ext of ['.webp', '.png']) {
    if (attackFiles.has(t + ext)) { attackBase[t] = t + ext; break; }
  }
}

// --- contiguous frame run per (subdir, type) -------------------------------
const SETS = [
  ['attack', BOSS], ['idle', BOSS], ['walk', BOSS],
  ['zodiac/attack', ZODIAC], ['zodiac/idle', ZODIAC], ['zodiac/walk', ZODIAC],
];
const frames = {};
let wasteNow = 0;
for (const [sub, types] of SETS) {
  const f = filesIn('Sprites/bosses/' + sub);
  frames[sub] = {};
  for (const t of types) {
    // The renderer ping-pongs the CONTIGUOUS run from index 0, so a gap ends
    // the usable run — count that way rather than counting files present.
    let n = 0;
    while (n < MAX && f.has(`${t}_${n}.webp`)) n++;
    if (n > 0) frames[sub][t] = n;
    wasteNow += (MAX - n);
  }
}
for (const t of BOSS) if (!attackBase[t]) wasteNow += attackFiles.has(t + '.png') ? 1 : 2;

const body = `// GENERATED by scripts/gen_boss_sprite_index.mjs - do not hand-edit.
// Which optional boss/zodiac sprites exist on disk. The loaders read this to
// skip requests for art that was never authored; when this file is absent they
// fall back to probing, so an old build still works.
//   attackBase[type]   -> filename of the single static attack pose, or absent
//   frames[subdir][type] -> count of contiguous frames from _0, or absent (none)
window.LX_BOSS_SPRITE_INDEX = ${JSON.stringify({ attackBase, frames }, null, 1)};
`;

if (CHECK) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur.trim() !== body.trim()) {
    console.error('STALE: ' + OUT + ' does not match disk. Run: node scripts/gen_boss_sprite_index.mjs');
    process.exit(1);
  }
  console.log(OUT + ' is up to date.');
  process.exit(0);
}

const tmp = OUT + '.tmp';
writeFileSync(tmp, body, 'utf8');
renameSync(tmp, OUT);

const nBase = Object.keys(attackBase).length;
const nFrameSets = Object.values(frames).reduce((a, o) => a + Object.keys(o).length, 0);
console.log(`wrote ${OUT}`);
console.log(`  base attack poses: ${nBase}/${BOSS.length} boss types`);
console.log(`  frame sets indexed: ${nFrameSets}`);
console.log(`  guaranteed 404s this removes per cold boot: ${wasteNow}`);
