#!/usr/bin/env node
// Build anim_calib_manifest.js for monster_animator.html.
// =============================================================================
// Scans Sprites/{monsters,bosses}/{idle,walk,attack}/ for entities that have
// animation frames, pairs each with its base sprite (for the foot-anchor bbox
// the game uses), and emits a window.LX_ANIM_MANIFEST the tool reads. Run after
// adding/regenerating frames:  node scripts/gen_anim_manifest.mjs
// =============================================================================
import sharp from 'sharp';
import { readdir, writeFile, readFile, access } from 'node:fs/promises';
import { dirname, join, basename, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
sharp.cache(false);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const exists = async (p) => { try { await access(p); return true; } catch { return false; } };
const STATES = ['idle', 'walk', 'attack'];

// Alpha bbox-bottom fraction of a sprite (mirrors the game's foot anchor).
async function baseInfo(path) {
  try {
    const { data, info } = await sharp(await readFile(path)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    const W = info.width, H = info.height, C = info.channels;
    let bottom = 0;
    for (let y = H - 1; y >= 0; y--) { let hit = false; for (let x = 0; x < W; x++) if (data[(y * W + x) * C + 3] > 16) { hit = true; break; } if (hit) { bottom = y; break; } }
    return { w: W, h: H, botFrac: +(((bottom + 1) / H).toFixed(4)) };
  } catch { return null; }
}

async function scanGroup(group, dir) {
  // discover entity types from the idle/walk/attack subdirs
  const types = new Set();
  for (const st of STATES) {
    const sdir = join(dir, st);
    if (!(await exists(sdir))) continue;
    for (const f of await readdir(sdir)) {
      const m = f.match(/^(.+)_(\d+)\.webp$/i);
      if (m) types.add(m[1]);
    }
  }
  const out = {};
  for (const type of types) {
    // base sprite (for the foot-anchor bbox) — png then webp
    let base = null, basePath = null;
    for (const ext of ['.png', '.webp']) {
      const p = join(dir, type + ext);
      if (await exists(p)) { base = await baseInfo(p); basePath = `Sprites/${group === 'boss' ? 'bosses' : 'monsters'}/${type}${ext}`; break; }
    }
    const states = {};
    for (const st of STATES) {
      let count = 0; let dims = null;
      while (await exists(join(dir, st, `${type}_${count}.webp`))) {
        if (count === 0) { try { const mm = await sharp(await readFile(join(dir, st, `${type}_0.webp`))).metadata(); dims = { w: mm.width, h: mm.height }; } catch {} }
        count++;
      }
      if (count) states[st] = { count, ...(dims || {}), dir: `Sprites/${group === 'boss' ? 'bosses' : 'monsters'}/${st}/${type}` };
    }
    if (Object.keys(states).length) out[type] = { group, base, basePath, states };
  }
  return out;
}

const manifest = {
  ...(await scanGroup('monster', join(root, 'Sprites', 'monsters'))),
  ...(await scanGroup('boss', join(root, 'Sprites', 'bosses'))),
};
const n = Object.keys(manifest).length;
await writeFile(join(root, 'anim_calib_manifest.js'),
  '// AUTO-GENERATED by scripts/gen_anim_manifest.mjs — do not hand-edit.\n' +
  '// Lists every animated entity (monster/boss) + its base foot-anchor bbox +\n' +
  '// per-state frame info, for monster_animator.html.\n' +
  'window.LX_ANIM_MANIFEST = ' + JSON.stringify(manifest, null, 0) + ';\n');
console.log(`Wrote anim_calib_manifest.js — ${n} animated entities.`);
