#!/usr/bin/env node
// Gravitos IDLE, generated by ludo.ai, with a chosen pose pinned at frame 4.
// =============================================================================
// Per user: "what i meant is that this attach image should be the frame 4 of a
// 9 frame animation, please regenerate with ludo.ai accordingly". The pose is
// Sprites/bosses/attack/gravitos.webp - the wide planted stance, fists up.
//
// This replaces an earlier procedural attempt that composited the pose and
// computed a breath around it. That satisfied "frame 4 is this pose" by
// construction but was not an animation - the user wants ludo to actually
// animate him, so ludo animates him.
//
// SHAPE OF THE RUN, and why each step is here:
//   1. animateSprite from the pose, 9 frames (the API only takes perfect
//      squares - 4, 9, 16 - so 9 is the count, matching every other boss set).
//      The motion prompt is generate_boss_idle_anim.mjs's gravitos override
//      verbatim: it was written after form-1 came back with duplicated and
//      detached legs, and it locks the anatomy.
//   2. Rebase each returned frame onto the real 1656x1505 boss canvas with the
//      feet on the same foot line the shipped set uses (bottom row 1503, zero
//      drift across the set). Ludo returns its own framing; the engine's
//      foot-anchor chain assumes ours.
//   3. Pin frame 4 to the SOURCE pose exactly. Ludo will not reproduce an input
//      image to the pixel, and the request is specific about that frame, so it
//      is composited rather than hoped for.
//   4. Gate before installing: right canvas, nothing clipped at an edge, no two
//      adjacent frames identical, feet aligned. gen_aetherion_astral.mjs
//      records three ludo rolls that re-posed and cropped a boss, so the output
//      is checked rather than trusted.
//
//   node scripts/gen_gravitos_idle_ludo.mjs             # generate + gate, write candidates
//   node scripts/gen_gravitos_idle_ludo.mjs --install   # ...and install if the gates pass
//   node scripts/gen_gravitos_idle_ludo.mjs --from-cache --install   # re-run steps 2-4 on the last roll
// =============================================================================
import sharp from 'sharp';
import { readFile, writeFile, mkdir, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
sharp.cache(false);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'Sprites/bosses/attack/gravitos.webp');
const RAW = join(root, 'scripts', '_style_pack', 'anim_regen', 'gravitos_idle_ludo', 'raw');
const OUT = join(root, 'scripts', '_style_pack', 'anim_regen', 'gravitos_idle_ludo');
const DEST = join(root, 'Sprites/bosses/idle');
const argv = process.argv.slice(2);
const INSTALL = argv.includes('--install');
const FROM_CACHE = argv.includes('--from-cache');

const FRAMES = 9, MID = 4, FOOT_Y = 1503;
const API = process.env.LUDO_API_BASE || 'https://api.ludo.ai/api';
const key = process.env.LUDO_API_KEY;

const FACING = ' Keep the EXACT same left/right facing and orientation as the source image — never mirror or flip the character horizontally.';
// verbatim from generate_boss_idle_anim.mjs — written after form-1 came back
// with duplicated / detached legs
const MOTION = 'the cosmic-energy golem idles in place — gentle breathing, a slight sway, the chest core softly pulses '
  + 'and the arms flex subtly. It is ONE single connected body with EXACTLY two arms and two legs all attached to the '
  + 'torso; do NOT add, duplicate, split, mirror, or detach any limbs, and no floating body parts — the full body stays '
  + 'intact.' + FACING
  + ' He stays PLANTED: the feet do not leave the ground, he does not step, walk, lunge, jump or drift, and he stays the '
  + 'EXACT same size and position in frame — no zoom, no camera move, nothing cropped at any edge.';

const exists = async (p) => { try { await access(p); return true; } catch { return false; } };
async function post(path, body) {
  const res = await fetch(`${API}${path}`, {
    method: 'POST',
    headers: { Authorization: `ApiKey ${key}`, 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`${path} ${res.status}: ${(await res.text()).slice(0, 200)}`);
  return res.json();
}
const fetchBuf = async (u) => { const r = await fetch(u); if (!r.ok) throw new Error('fetch ' + r.status); return Buffer.from(await r.arrayBuffer()); };

// alpha bbox
async function box(buf) {
  const { data, info } = await sharp(buf).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const W = info.width, H = info.height;
  let t = -1, b = -1, l = W, r = -1;
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (data[(y * W + x) * 4 + 3] > 16) { if (t < 0) t = y; b = y; if (x < l) l = x; if (x > r) r = x; }
  }
  return t < 0 ? null : { W, H, t, b, l, r, w: r - l + 1, h: b - t + 1 };
}

// ---------- 1. generate ----------
await mkdir(RAW, { recursive: true });
if (!FROM_CACHE) {
  if (!key) { console.error('LUDO_API_KEY is not set'); process.exit(2); }
  const small = await sharp(await readFile(SRC)).resize(940, 940, { fit: 'inside', withoutEnlargement: true }).png().toBuffer();
  console.log('asking ludo for ' + FRAMES + ' idle frames from ' + SRC.split(/[\\/]/).pop() + ' ...');
  const data = await post('/assets/sprite/animate', {
    initial_image: 'data:image/png;base64,' + small.toString('base64'),
    motion_prompt: MOTION,
    frames: FRAMES, frame_size: -9, model: 'eagle',
    individual_frames: true, loop: true, image_type: 'sprite',
  });
  let bufs = [];
  if (data.spritesheet_url && data.num_cols && data.num_rows) {
    const sheet = await fetchBuf(data.spritesheet_url), meta = await sharp(sheet).metadata();
    const cw = Math.floor(meta.width / data.num_cols), ch = Math.floor(meta.height / data.num_rows);
    for (let r = 0; r < data.num_rows && bufs.length < FRAMES; r++)
      for (let c = 0; c < data.num_cols && bufs.length < FRAMES; c++)
        bufs.push(await sharp(sheet).extract({ left: c * cw, top: r * ch, width: cw, height: ch }).png().toBuffer());
  }
  if (bufs.length < FRAMES && (data.individual_frame_urls || []).length >= FRAMES) {
    bufs = []; for (let i = 0; i < FRAMES; i++) bufs.push(await fetchBuf(data.individual_frame_urls[i]));
  }
  if (bufs.length < FRAMES) { console.error('ludo returned ' + bufs.length + ' usable frames'); process.exit(1); }
  for (let i = 0; i < FRAMES; i++) await writeFile(join(RAW, 'raw_' + i + '.png'), bufs[i]);
  console.log('  got ' + bufs.length + ' frames -> ' + RAW);
} else {
  console.log('re-using the cached roll in ' + RAW);
}

// ---------- 2. rebase onto the boss canvas, feet on the foot line ----------
const srcBuf = await readFile(SRC);
const S = await box(srcBuf);
const meta = await sharp(srcBuf).metadata();
const CW = meta.width, CH = meta.height;
const CX = Math.round((S.l + S.r) / 2);
console.log('\nboss canvas ' + CW + 'x' + CH + '   source pose ' + S.w + 'x' + S.h + '  feet at ' + S.b);

await mkdir(OUT, { recursive: true });
const rows = [];
for (let i = 0; i < FRAMES; i++) {
  let out;
  if (i === MID) {
    // step 3 — the requested frame, composited exactly, not generated
    const layer = await sharp(srcBuf).extract({ left: S.l, top: S.t, width: S.w, height: S.h }).png().toBuffer();
    out = await sharp({ create: { width: CW, height: CH, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
      .composite([{ input: layer, left: Math.round(CX - S.w / 2), top: FOOT_Y - S.h + 1 }])
      .webp({ quality: 92, alphaQuality: 100 }).toBuffer();
  } else {
    const p = join(RAW, 'raw_' + i + '.png');
    if (!(await exists(p))) { console.error('missing ' + p); process.exit(1); }
    const raw = await readFile(p);
    const R = await box(raw);
    if (!R) { console.error('frame ' + i + ' is empty'); process.exit(1); }
    // scale the generated figure to the source pose's height, then plant it
    const k = S.h / R.h;
    const w = Math.max(1, Math.round(R.w * k)), h = Math.max(1, Math.round(R.h * k));
    const cropped = await sharp(raw).extract({ left: R.l, top: R.t, width: R.w, height: R.h })
      .resize({ width: w, height: h, fit: 'fill', kernel: 'lanczos3' }).png().toBuffer();
    const left = Math.round(CX - w / 2), top = FOOT_Y - h + 1;
    if (left < 0 || top < 0 || left + w > CW || top + h > CH) { console.error('frame ' + i + ' falls off the canvas'); process.exit(1); }
    out = await sharp({ create: { width: CW, height: CH, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
      .composite([{ input: cropped, left, top }])
      .webp({ quality: 92, alphaQuality: 100 }).toBuffer();
  }
  await writeFile(join(OUT, 'gravitos_' + i + '.webp'), out);
  const B = await box(out);
  rows.push({ i, t: B.t, b: B.b, h: B.h, w: B.w, mid: i === MID });
}

console.log('\n frame   top  bottom  height  width');
for (const r of rows) {
  console.log('   ' + r.i + '    ' + String(r.t).padStart(5) + '  ' + String(r.b).padStart(6)
    + '  ' + String(r.h).padStart(6) + '  ' + String(r.w).padStart(6) + (r.mid ? '   <- the requested pose, composited exactly' : ''));
}

// ---------- 4. gate ----------
const fails = [];
const feet = [...new Set(rows.map((r) => r.b))];
if (feet.length !== 1) fails.push('feet drift: bottoms ' + feet.join(','));
const bufs = [];
for (let i = 0; i < FRAMES; i++) bufs.push(await readFile(join(OUT, 'gravitos_' + i + '.webp')));
const hashes = await Promise.all(bufs.map(async (b) => {
  const { data } = await sharp(b).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  let h = 0; for (let i = 3; i < data.length; i += 4 * 97) h = (h * 31 + data[i]) | 0;
  return h;
}));
for (let i = 0; i < FRAMES - 1; i++) if (hashes[i] === hashes[i + 1]) fails.push('frames ' + i + ' and ' + (i + 1) + ' are identical');
for (const r of rows) {
  const m = Math.min(r.t, CW - 1 - (Math.round(CX + r.w / 2)), Math.round(CX - r.w / 2));
  if (r.t < 4) fails.push('frame ' + r.i + ' touches the top edge');
  if (Math.round(CX - r.w / 2) < 4) fails.push('frame ' + r.i + ' touches the left edge');
}
const hs = rows.map((r) => r.h);
const spread = Math.max(...hs) / Math.min(...hs);
console.log('\nfeet pinned        : ' + (feet.length === 1 ? 'yes, bottom=' + feet[0] : 'NO'));
console.log('distinct frames    : ' + new Set(hashes).size + '/' + FRAMES);
console.log('height spread      : ' + spread.toFixed(3) + 'x  (' + Math.min(...hs) + '..' + Math.max(...hs) + 'px)');
console.log('frame ' + MID + ' is the pose : ' + (rows[MID].h === S.h && rows[MID].w === S.w));
if (fails.length) {
  console.log('\nGATE FAILED:');
  for (const f of [...new Set(fails)]) console.log('   ' + f);
  console.log('\ncandidates left in ' + OUT + ' — NOT installed.');
  process.exit(1);
}
console.log('\ngates passed.');
if (INSTALL) {
  for (let i = 0; i < FRAMES; i++) await writeFile(join(DEST, 'gravitos_' + i + '.webp'), bufs[i]);
  console.log('installed -> Sprites/bosses/idle/gravitos_0..8.webp');
} else {
  console.log('candidates in ' + OUT + '  (re-run with --install to write them over the set)');
}
