#!/usr/bin/env node
// THE MAP PIN (emoji 1f4cd), redrawn with Guguma's face on it.
// ============================================================================
// Per user, of the old icon: "regenerate the sprite for this pin, it needs to look more 2D and
// vertical and make sure it has guguma's face imprinted on it". The shipped one was a three-quarter
// 3D push-pin lying at an angle - at the 14-18 px it is actually drawn at (inline in quest lines,
// map markers, the world map) it read as a blob.
//
// The pin BODY is generated by ludo.ai (same contract as gen_emoji_icons.mjs: POST /assets/image ->
// 202 + job, poll /assets/jobs/<id>); Guguma's FACE is not generated - it is cropped from his own
// sprite (Sprites/npc/Guguma.webp) and stamped onto the pin's head, so the likeness is exactly his.
//
//   LUDO_API_KEY=... node scripts/gen_guguma_pin.mjs --gen [--n=4]     # candidates -> review dir
//   node scripts/gen_guguma_pin.mjs --compose --pick=2 [--face=..] [--cx=0.5 --cy=0.40 --fs=0.46]
//   node scripts/gen_guguma_pin.mjs --install --from=<png>             # -> Sprites/ui/emoji/1f4cd.webp
// After installing, repack the atlas (see the packer named in scripts/apply_no_emoji.mjs).
import sharp from 'sharp';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
sharp.cache(false);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REVIEW = path.join(ROOT, 'scripts', '_tmp_pin_review');
const KEY = process.env.LUDO_API_KEY, API = process.env.LUDO_API_BASE || 'https://api.ludo.ai/api';
const arg = (k, d) => { const a = process.argv.find((x) => x.startsWith('--' + k + '=')); return a ? a.slice(k.length + 3) : d; };
const has = (f) => process.argv.includes('--' + f);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
fs.mkdirSync(REVIEW, { recursive: true });

// Flat, upright, front-on: the three things the old icon was not. No face is asked for - the head is
// wanted EMPTY so Guguma can be stamped into it.
const PROMPT = 'A single map pin icon seen flat from the front, perfectly upright and vertical: a large round ' +
  'golden-amber disc head at the top with a plain smooth empty centre, and a short straight silver needle ' +
  'pointing straight down from the bottom of the disc. Completely flat 2D vector game icon, front view, no ' +
  'perspective, no tilt, no angle, no 3D, symmetrical left to right. Bold clean dark outline, soft cel shading, ' +
  'vivid saturated colours, centered, fills the frame, one object only, no text, no letters, no background.';

async function ludoImage() {
  const res = await fetch(`${API}/assets/image`, { method: 'POST', headers: { Authorization: `ApiKey ${KEY}`, 'Content-Type': 'application/json' }, signal: AbortSignal.timeout(120000),
    body: JSON.stringify({ image_type: 'sprite', art_style: 'Anime/Manga', aspect_ratio: 'ar_1_1', n: 1, augment_prompt: false, prompt: PROMPT }) });
  if (res.status === 402) throw new Error('OUT OF CREDITS (402)');
  const txt = await res.text();
  if (!res.ok) throw new Error(`POST ${res.status}: ${txt.slice(0, 140)}`);
  let j = JSON.parse(txt);
  const urlOf = (d) => Array.isArray(d) ? (d[0] && d[0].url) : (d && (d.url || (d.images && d.images[0] && d.images[0].url) || (Array.isArray(d.result) && d.result[0] && d.result[0].url)));
  if (!urlOf(j)) {
    const id = j.id; if (!id) throw new Error('neither url nor job: ' + txt.slice(0, 120));
    for (let i = 0; i < 60; i++) {
      await sleep(Math.max(4000, Number(j.poll_after_ms) || 5000));
      const r = await fetch(`${API}/assets/jobs/${id}`, { headers: { Authorization: `ApiKey ${KEY}` }, signal: AbortSignal.timeout(30000) });
      if (r.status === 429) { await r.text().catch(() => {}); continue; }
      j = await r.json();
      if (j.status === 'succeeded') break;
      if (j.status === 'failed' || j.status === 'cancelled') throw new Error('job ' + j.status);
    }
  }
  const url = urlOf(j); if (!url) throw new Error('job done but no url');
  const dl = await fetch(url, { signal: AbortSignal.timeout(120000) });
  return Buffer.from(await dl.arrayBuffer());
}

// the icon pipeline gen_emoji_icons.mjs uses: trim the transparent margin, fit at 86% into 128x128
async function toIcon(buf, size = 128) {
  const trimmed = await sharp(buf).ensureAlpha().trim({ threshold: 8 }).png().toBuffer();
  const inner = Math.round(size * 0.86);
  const fitted = await sharp(trimmed).resize(inner, inner, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer();
  return sharp({ create: { width: size, height: size, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite([{ input: fitted, gravity: 'center' }]).png().toBuffer();
}
async function sheet(files, out, label = true) {
  const cells = [];
  for (const [i, f] of files.entries()) {
    cells.push({ input: await sharp(f).resize(160, 160, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer(), left: 12 + i * 176, top: 12 });
    if (label) for (const [k, s] of [[0, 48], [1, 32], [2, 20]]) cells.push({ input: await sharp(f).resize(s, s, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer(), left: 12 + i * 176 + k * 56, top: 190 });
  }
  await sharp({ create: { width: 24 + files.length * 176, height: 250, channels: 4, background: { r: 38, g: 42, b: 58, alpha: 1 } } }).composite(cells).png().toFile(out);
  console.log('sheet ->', path.relative(ROOT, out));
}

if (has('gen')) {
  if (!KEY) { console.error('LUDO_API_KEY is not set'); process.exit(1); }
  const n = Number(arg('n', 4)), made = [];
  for (let i = 1; i <= n; i++) {
    process.stdout.write(`pin candidate ${i} ... `);
    try { const raw = await ludoImage(); fs.writeFileSync(path.join(REVIEW, `raw_${i}.png`), raw);
      const f = path.join(REVIEW, `pin_${i}.png`); fs.writeFileSync(f, await toIcon(raw)); made.push(f); console.log('ok'); }
    catch (e) { console.log('failed: ' + e.message); if (/402/.test(e.message)) break; }
  }
  if (made.length) await sheet(made, path.join(REVIEW, 'candidates.png'));
}

// ---- Guguma's face, stamped into the pin's head -----------------------------------------------
// His face is CROPPED from his own sprite, never generated: the likeness has to be exactly his.
const FACE_BOX = { left: 372, top: 290, width: 360, height: 360 };   // eyes + beak in Sprites/npc/Guguma.webp
async function stampFace(pinPng, { cx = 0.5, cy = 0.375, fs: fsz = 0.36 } = {}) {
  const S = 512;
  const pin = await sharp(pinPng).resize(S, S, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer();
  const d = Math.round(fsz * S), left = Math.round(cx * S - d / 2), top = Math.round(cy * S - d / 2);
  const face = await sharp(path.join(ROOT, 'Sprites/npc/Guguma.webp')).extract(FACE_BOX).resize(d, d, { fit: 'cover' }).png().toBuffer();
  const circle = Buffer.from(`<svg width="${d}" height="${d}"><circle cx="${d / 2}" cy="${d / 2}" r="${d / 2 - 1}" fill="#fff"/></svg>`);
  const disc = await sharp(face).composite([{ input: circle, blend: 'dest-in' }]).png().toBuffer();
  // a dark rim and a shadow falling from the top edge: the face sits IN the head, not on it
  const rim = Buffer.from(`<svg width="${d}" height="${d}" xmlns="http://www.w3.org/2000/svg">
    <defs><radialGradient id="s" cx="0.5" cy="0.34" r="0.72">
      <stop offset="0.55" stop-color="#000" stop-opacity="0"/><stop offset="1" stop-color="#000" stop-opacity="0.38"/>
    </radialGradient></defs>
    <circle cx="${d / 2}" cy="${d / 2}" r="${d / 2 - 1}" fill="url(#s)"/>
    <circle cx="${d / 2}" cy="${d / 2}" r="${d / 2 - 2}" fill="none" stroke="#2b1a05" stroke-opacity="0.85" stroke-width="${Math.max(3, d * 0.045)}"/>
  </svg>`);
  const composed = await sharp(pin).composite([{ input: disc, left, top }, { input: rim, left, top }]).png().toBuffer();
  // clip anything that spilled past the pin's own silhouette (sharp resizes BEFORE it composites in
  // one chain, so the clip and the downsample are separate calls)
  const mask = await sharp(pin).extractChannel('alpha').png().toBuffer();
  const clipped = await sharp(composed).composite([{ input: mask, blend: 'dest-in' }]).png().toBuffer();
  return sharp(clipped).resize(128, 128).png().toBuffer();
}

if (has('compose')) {
  const pick = arg('pick', '3');
  const out = path.join(REVIEW, `composed_${pick}.png`);
  fs.writeFileSync(out, await stampFace(path.join(REVIEW, `pin_${pick}.png`), { cx: Number(arg('cx', 0.5)), cy: Number(arg('cy', 0.375)), fs: Number(arg('fs', 0.36)) }));
  console.log('composed ->', path.relative(ROOT, out));
  await sheet([out], path.join(REVIEW, 'composed_sheet.png'));
}

if (has('install')) {
  const from = arg('from', path.join(REVIEW, 'composed_3.png'));
  const png = fs.readFileSync(from);
  const dst = path.join(ROOT, 'Sprites/ui/emoji/1f4cd.webp');
  // same encode as gen_emoji_icons.mjs, and the raw copy is refreshed so a re-pack reproduces this art
  await sharp(png).webp({ quality: 90, alphaQuality: 100 }).toFile(dst + '.tmp');
  fs.renameSync(dst + '.tmp', dst);
  const rawDir = path.join(ROOT, 'Sprites/ui/emoji/raw');   // kept out of git; only refreshed when it is there
  if (fs.existsSync(rawDir)) fs.writeFileSync(path.join(rawDir, '1f4cd.png'), png);
  console.log('installed Sprites/ui/emoji/1f4cd.webp — now run: node scripts/pack_emoji_atlas.mjs');
}
