#!/usr/bin/env node
// Precompute sprite BBOX metrics into data/sprite_bbox.js.
//
// WHY: profiling a 29-mob fight showed 5.7 s of the run blocked inside
// getImageData, and the two bbox scanners were 3.2 s of it. Cutting the pixels
// they read by 83% (band scanning) bought only 7% of the time — because the
// cost is the per-call GPU->CPU sync stall, ~7 ms EVERY call regardless of
// size. The only way to win is to not call it at runtime at all.
//
// This replicates the two runtime scans EXACTLY — same alpha thresholds, same
// two-opaque-pixel run rule, same fallbacks — so the table is a drop-in answer
// rather than an approximation. scripts/sprite_bbox_test.mjs proves that in the
// browser by comparing table values against live scans.
//
// Edge-feather data is deliberately NOT precomputed: that probe downscales to
// 48x48 through the browser's own resampler, and sharp's resize would not match
// it pixel for pixel. Wrong feather is a visible regression; it keeps its
// runtime probe (now budgeted per frame instead).
//
//   node scripts/gen_sprite_bbox.mjs            # write data/sprite_bbox.js
//   node scripts/gen_sprite_bbox.mjs --check    # exit 1 if the table is stale
import { readdirSync, statSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, relative } from 'node:path';
import sharp from 'sharp';
sharp.cache(false);

const ROOT = 'C:/Users/dpeh0/Mojiworld';
const OUT = join(ROOT, 'data', 'sprite_bbox.js');
const CHECK = process.argv.includes('--check');
// Only the trees whose sprites actually reach the two scanners.
const DIRS = ['monsters', 'bosses', 'objects', 'npc'];
const SKIP = (n) => n.startsWith('_') || /backup/i.test(n) || /^pre_\d/.test(n) || n === 'Todo list';

const files = [];
const walk = (d) => {
  for (const e of readdirSync(d, { withFileTypes: true })) {
    if (SKIP(e.name)) continue;
    const p = join(d, e.name);
    if (e.isDirectory()) walk(p);
    else if (e.name.endsWith('.webp') || e.name.endsWith('.png')) files.push(p);
  }
};
for (const d of DIRS) { const p = join(ROOT, 'Sprites', d); if (existsSync(p)) walk(p); }
files.sort();

// --- the two scans, replicated exactly from mojiworld_game.html -------------
// bottom: alpha > 64, needs TWO consecutive opaque px in a row, scanning up.
//         no hit -> height - 1.
// top:    alpha > 12, first opaque px scanning down. no hit -> 0.
async function metrics(file) {
  const { data, info } = await sharp(readFileSync(file)).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width: W, height: H, channels: C } = info;
  const A = (x, y) => data[(y * W + x) * C + 3];
  let bot = H - 1;
  outer: for (let y = H - 1; y >= 0; y--) {
    let run = 0;
    for (let x = 0; x < W; x++) {
      if (A(x, y) > 64) { if (++run >= 2) { bot = y; break outer; } } else run = 0;
    }
  }
  let top = 0;
  outer2: for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) { if (A(x, y) > 12) { top = y; break outer2; } }
  }
  return [top, bot, W, H];
}

const table = {};
let n = 0;
for (const f of files) {
  const key = relative(join(ROOT, 'Sprites'), f).split('\\').join('/');
  try { table[key] = await metrics(f); } catch (e) { /* unreadable art is skipped, runtime falls back */ }
  if (++n % 500 === 0) process.stdout.write(`  ${n}/${files.length}\r`);
}

// Compact: "top,bot,w,h" strings keep the file a third of the JSON-array size.
const flat = {};
for (const k of Object.keys(table).sort()) flat[k] = table[k].join(',');
const body = `// GENERATED by scripts/gen_sprite_bbox.mjs — do not hand-edit.
// Opaque-content bounds per sprite: "bboxTop,bboxBottom,width,height".
// Runtime reads this instead of a getImageData scan; see _detectSpriteBboxTop /
// _detectSpriteBboxBottom in mojiworld_game.html. Regenerate after any art drop
// under Sprites/{monsters,bosses,objects,npc}: node scripts/gen_sprite_bbox.mjs
window.LX_SPRITE_BBOX = ${JSON.stringify(flat)};
`;

if (CHECK) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur.trim() !== body.trim()) { console.error(`STALE: ${OUT} differs — re-run without --check`); process.exit(1); }
  console.log(`sprite_bbox.js is current (${Object.keys(flat).length} sprites)`);
  process.exit(0);
}
writeFileSync(OUT, body);
console.log(`\nwrote ${OUT}: ${Object.keys(flat).length} sprites, ${(body.length / 1024).toFixed(0)} KB`);
