// Per-boss columnStrike STRIKE-BEAM art for casters that never had any.
// ============================================================================
// Per user, with a screenshot of Barnaby's column rendering as a flat pale
// gradient bar: "this column has no sprites ... ensure that all other bosses
// column has sprites for the column".
//
// The beam is driven purely by the caster's `columnStrike.sprite` field —
// drawProjectiles does `LX_FX[p._colSprite]` and, when that is null or the
// asset has not decoded, falls through to the procedural gradient. An audit of
// all 13 columnStrike declarations found exactly ONE with no sprite at all:
//   young_confused_barnaby -> columnStrike:{ dmgMul:1.6, width:115, ... }
// He already HAS a telegraph (tg_col_young_confused_barnaby, generated by
// gen_col_telegraphs.mjs) — so the warning pillar was themed and the strike
// that followed it was the generic bar. This makes the missing half.
//
// Same recipe as gen_zodiac_column_fx.mjs: identical BEAM_BASE / BEAM_TAIL, the
// same 512x1120 canvas at ~66% content width, the same alpha feather, and the
// same hard assertion that ZERO opaque pixels touch any border (the cutoff rule
// in docs/prompts/sprite_column_strike.md, which the older shared art broke).
//
//   node scripts/gen_boss_column_fx.mjs            # dry-run, print the plan
//   node scripts/gen_boss_column_fx.mjs --generate # call Ludo (LUDO_API_KEY)
//   flags: --only barnaby   --force
import { mkdir, writeFile, rename, access } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';
sharp.cache(false);
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(repoRoot, 'Sprites', 'fx');
const API = process.env.LUDO_API_BASE || 'https://api.ludo.ai/api';
const apiKey = process.env.LUDO_API_KEY;
const has = (f) => process.argv.includes(f);
const arg = (f) => { const i = process.argv.indexOf(f); return i >= 0 ? process.argv[i + 1] : null; };
const exists = async (p) => { try { await access(p); return true; } catch { return false; } };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// Verbatim from gen_zodiac_column_fx.mjs so every beam in the game reads as
// one family. Do not "improve" one copy without the other.
const BEAM_BASE = 'game vfx sprite, a single tall vertical column of energy centered horizontally, '
  + 'filling the frame top to bottom, bright hot core down the centerline about 30% of the width, '
  + 'soft translucent falloff on the left and right so it reads as light rather than a solid slab, ';
const BEAM_TAIL = ', the motif is a repeating flowing vertical pattern that survives being stretched '
  + 'tall - rising motes and drifting bands, no single large hero element that would smear. '
  + '16-bit painterly VFX, vibrant, faint inner edge glow. Pure transparent background, alpha only: '
  + 'no scene, no ground, no character, no platform, no text, no letters, no numbers, no watermark.';

const JOBS = [
  {
    key: 'barnaby',
    file: 'fx_col_barnaby.webp',
    W: 512, H: 1120, contentW: 0.66, featherX: 0.06, featherY: 0.05,
    // Matches his own palette (color #d8c878 sandy gold over shell #6a4a18 dark
    // brown) and the theme his telegraph already established: "lost-sentinel
    // sandstone". He is the sentinel who never picked which wall to defend, so
    // the beam is two strands of light that keep crossing and never settle.
    // v1 of this prompt asked for "two slender strands braiding" and the model
    // drew exactly that: a thin wavy filament, not a column. Beside the other
    // beams it read as a wire. The braid is now an INTERNAL motif inside a
    // full-width shaft, which is how arbiter/sovereign/legosaurus are built.
    beam: 'lost-sentinel sandstone theme: a WIDE THICK column that fills the full width of the '
      + 'frame edge to edge, heavy solid shaft of warm dusty gold and pale sandstone light '
      + '(#d8c878) with deep worn-brown edge shading (#6a4a18) down both sides. INSIDE the broad '
      + 'shaft, two brighter ribbons of light wind slowly around each other as if the column '
      + 'cannot decide which way to face, with drifting sand motes and small crumbling watchtower '
      + 'brick flecks rising through it and a faint worn stone sigil glow. Broad and imposing like '
      + 'a falling pillar of light, not a thin beam and not a wire',
  },
  {
    key: 'conductor',
    file: 'fx_col_conductor.webp',
    W: 512, H: 1120, contentW: 0.66, featherX: 0.06, featherY: 0.05,
    // The Master Conductor was the last BOSS drawing another boss's beam:
    // v0.30.281 gave his DEPARTURE SIGNAL the Arbiter's golden judgement
    // column, deliberately ("the judgment of a missed departure"). The idea is
    // good and is kept - this is still a signal falling on you - but rendered
    // in HIS palette (color #88aaee over shell #2a3a8a) instead of the Tower's
    // gold, so a clockwork train guard stops firing the Spire's law.
    // v1 of this prompt led with the clockwork and the model built a solid
    // mechanical grille - a dark machine wall, not a strike. Every other beam
    // in the game reads as LIGHT first. The gears are now ghostly shapes
    // suspended inside a luminous shaft rather than the structure itself.
    beam: 'clockwork railway DEPARTURE SIGNAL theme: a WIDE THICK column of BRIGHT GLOWING LIGHT '
      + 'that fills the full width of the frame edge to edge, blazing white-hot core down the '
      + 'centre, cold signal-lamp blue (#88aaee) mid-body, deep navy (#2a3a8a) only at the soft '
      + 'translucent outer falloff, with a warm brass-amber glint threaded through the core. '
      + 'It is a pillar of luminous energy, glowing and semi-transparent like a searchlight beam. '
      + 'FAINT and GHOSTLY inside the glow, barely visible as darker silhouettes suspended in the '
      + 'light: slowly turning clock hands, a few brass gear outlines, small punched ticket stubs '
      + 'and drifting steam wisps rising. The clockwork is a subtle hint inside the light, NOT a '
      + 'solid machine, NOT a metal grille, NOT a wall of gears. Bright, radiant and imposing',
  },
];

async function fetchBuf(url) {
  const r = await fetch(url, { signal: AbortSignal.timeout(120000) });
  if (!r.ok) throw new Error('fetch ' + r.status);
  return Buffer.from(await r.arrayBuffer());
}

async function feather(buf, W, H, fx, fy) {
  const { data, info } = await sharp(buf).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const px = Math.max(1, Math.round(W * fx)), py = Math.max(1, Math.round(H * fy));
  const C = info.channels;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      const dx = Math.min(x, W - 1 - x), dy = Math.min(y, H - 1 - y);
      let k = 1;
      if (dx < px) k = Math.min(k, dx / px);
      if (dy < py) k = Math.min(k, dy / py);
      if (dx === 0 || dy === 0) k = 0;                 // border ring is always clear
      if (k < 1) { const i = (y * W + x) * C + 3; data[i] = Math.round(data[i] * k); }
    }
  }
  return sharp(data, { raw: { width: W, height: H, channels: C } }).png().toBuffer();
}

async function gen(job) {
  const dest = join(DIR, job.file);
  if (!has('--force') && await exists(dest)) { console.log(`  ${job.file} exists — skip`); return; }
  let lastErr;
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const ratio = attempt >= 3 ? 'ar_1_1' : 'ar_9_16';
      const res = await fetch(`${API}/assets/image`, {
        method: 'POST',
        headers: { Authorization: `ApiKey ${apiKey}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ image_type: 'sprite', art_style: 'Anime/Manga', aspect_ratio: ratio,
                               n: 1, augment_prompt: false, prompt: BEAM_BASE + job.beam + BEAM_TAIL }),
        signal: AbortSignal.timeout(120000),
      });
      if (!res.ok) throw new Error(`image ${res.status}: ${(await res.text()).slice(0, 140)}`);
      const data = await res.json();
      const url = Array.isArray(data) ? data[0]?.url : (data?.url || data?.images?.[0]?.url);
      if (!url) throw new Error('no url in response');
      const raw = await fetchBuf(url);
      let content; try { content = await sharp(raw).trim().toBuffer(); } catch { content = raw; }
      const cw = Math.round(job.W * job.contentW);
      const inner = await sharp(content).resize(cw, job.H, { fit: 'fill' }).png().toBuffer();
      const canvas = await sharp({ create: { width: job.W, height: job.H, channels: 4,
                                             background: { r: 0, g: 0, b: 0, alpha: 0 } } })
        .composite([{ input: inner, left: Math.round((job.W - cw) / 2), top: 0 }]).png().toBuffer();
      const feathered = await feather(canvas, job.W, job.H, job.featherX, job.featherY);
      const out = await sharp(feathered).webp({ quality: 92 }).toBuffer();
      // Assert: no opaque pixel on any border, and it is not a solid slab.
      const { data: p2, info: i2 } = await sharp(out).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
      const A = (x, y) => p2[(y * i2.width + x) * i2.channels + 3];
      let border = 0, clear = 0;
      for (let x = 0; x < i2.width; x++) { if (A(x, 0) > 16) border++; if (A(x, i2.height - 1) > 16) border++; }
      for (let y = 0; y < i2.height; y++) { if (A(0, y) > 16) border++; if (A(i2.width - 1, y) > 16) border++; }
      for (let i = 3; i < p2.length; i += 4) if (p2[i] < 20) clear++;
      const pct = (100 * clear / (i2.width * i2.height));
      if (border !== 0) throw new Error(`border bleed ${border}px after feather`);
      await mkdir(DIR, { recursive: true });
      await writeFile(dest + '.tmp', out); await rename(dest + '.tmp', dest);
      console.log(`  ok -> ${job.file} ${i2.width}x${i2.height} ${out.length}b, transparent ${pct.toFixed(1)}%, border 0 (ratio ${ratio})`);
      if (pct < 8) console.warn(`     WARNING: ${job.file} is nearly opaque — inspect it`);
      return;
    } catch (e) { lastErr = e; if (attempt < 4) await sleep(3000 * attempt); }
  }
  console.error(`  FAIL ${job.file}: ${lastErr && lastErr.message}`);
  process.exitCode = 2;
}

const only = arg('--only');
const jobs = JOBS.filter((j) => !only || only.split(',').includes(j.key));
if (!has('--generate')) {
  console.log('# boss column STRIKE beams (ludo.ai)\n');
  for (const j of jobs) console.log(`  ${j.key.padEnd(10)} -> Sprites/fx/${j.file}  ${j.W}x${j.H}`);
  console.log('\n# Re-run with --generate (needs LUDO_API_KEY). Flags: --only <keys> --force');
  process.exit(0);
}
if (!apiKey) { console.error('LUDO_API_KEY not set'); process.exit(1); }
console.log(`generating ${jobs.length} boss column beam(s)...`);
for (const j of jobs) { await gen(j); await sleep(800); }
console.log('done.');
