// Bake which optional sprite frames actually exist, so the loaders stop
// requesting art that was never authored.
//
// Every animation loader in the game walks a fixed grid: <key>_0 .. _8. It
// cannot tell "absent" from "not decoded yet" without asking, so each missing
// set costs 9 guaranteed 404s. Measured before this existed:
//   bosses (eager, every boot) .... 30
//   npc/walk (lazy, per NPC drawn)  387   <- 43 of 44 NPCs have no walk art
//   projectiles/anim ............... 9    <- 'firebomb' allowlisted, never drawn
//   partial sets (1 frame of 9) .... 16
//
//   node scripts/gen_sprite_frame_index.mjs           # write the baked file
//   node scripts/gen_sprite_frame_index.mjs --check   # exit 1 if stale
//
// Re-run after dropping new art; --check is the drift guard.
import { readFileSync, writeFileSync, renameSync, existsSync, readdirSync } from 'node:fs';

const GAME = 'mojiworld_game.html';
const OUT = 'data/sprite_frame_index.js';
const MAX = 9;
const CHECK = process.argv.includes('--check');
const src = readFileSync(GAME, 'utf8');

// STRICT quoting: a loose /'([^']+)'/ swallows apostrophes inside comments
// ("doesn't exist") and turns whole comment blobs into fake keys.
const arrOf = (name) => {
  const m = src.match(new RegExp('const ' + name + '\\s*=\\s*\\[([\\s\\S]*?)\\];'));
  return m ? [...m[1].matchAll(/'([A-Za-z0-9_]+)'/g)].map(x => x[1]) : [];
};

// Every directory that holds <key>_<n>.webp frame sets. Indexing the DIRECTORY
// (rather than a key list) means art that lands later is picked up by a
// regenerate, and keys the game never asks for cost nothing.
const FRAME_DIRS = [
  'bosses/attack', 'bosses/idle', 'bosses/walk',
  'bosses/zodiac/attack', 'bosses/zodiac/idle', 'bosses/zodiac/walk',
  'monsters/idle', 'monsters/walk', 'monsters/attack',
  'npc/idle', 'npc/walk',
  'fx/anim', 'vfx/anim', 'projectiles/anim', 'summons/anim',
];

const frames = {};
let sets = 0;
for (const d of FRAME_DIRS) {
  const dir = 'Sprites/' + d;
  if (!existsSync(dir)) { frames[d] = {}; continue; }
  const files = new Set(readdirSync(dir));
  const keys = new Set();
  for (const f of files) { const m = f.match(/^(.*)_(\d+)\.webp$/); if (m) keys.add(m[1]); }
  const out = {};
  for (const k of keys) {
    // The renderers use the CONTIGUOUS run from index 0, so a gap ends the
    // usable set — count that way, not by how many files carry the prefix.
    let n = 0;
    while (n < MAX && files.has(`${k}_${n}.webp`)) n++;
    if (n > 0) { out[k] = n; sets++; }
  }
  frames[d] = out;
};

// Boss single-frame attack pose (not part of any _0.._8 set).
const attackFiles = existsSync('Sprites/bosses/attack') ? new Set(readdirSync('Sprites/bosses/attack')) : new Set();
const attackBase = {};
for (const t of arrOf('BOSS_SPRITE_TYPES')) {
  for (const ext of ['.webp', '.png']) if (attackFiles.has(t + ext)) { attackBase[t] = t + ext; break; }
}

const body = `// GENERATED by scripts/gen_sprite_frame_index.mjs - do not hand-edit.
// Which optional sprite frames exist on disk, so the animation loaders request
// only what is there instead of probing a fixed <key>_0.._8 grid.
//   frames["<dir>"]["<key>"] -> contiguous frame count from _0 (absent = none)
//   attackBase["<bossType>"] -> filename of the static attack pose (absent = none)
// Missing file => every loader falls back to probing, so an older build runs.
window.LX_SPRITE_FRAME_INDEX = ${JSON.stringify({ frames, attackBase }, null, 1)};
`;

if (CHECK) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur.trim() !== body.trim()) {
    console.error('STALE: ' + OUT + ' does not match disk. Run: node scripts/gen_sprite_frame_index.mjs');
    process.exit(1);
  }
  console.log(OUT + ' is up to date.');
  process.exit(0);
}
const tmp = OUT + '.tmp';
writeFileSync(tmp, body, 'utf8');
renameSync(tmp, OUT);
console.log(`wrote ${OUT}`);
console.log(`  frame dirs indexed: ${FRAME_DIRS.length}`);
console.log(`  frame sets: ${sets}`);
console.log(`  boss base attack poses: ${Object.keys(attackBase).length}`);
