#!/usr/bin/env node
// Precompute the seamless-tile crop rects into data/tile_crops.js.
// ============================================================================
// _lxBakeSeamlessTile spends 713-2247 ms of boot on getImageData, and the cost
// is per CALL, not per pixel: the first readback after a drawImage flushes the
// GPU pipeline (~14 ms) even for a one-row read — which is why the v0.30.245
// band-scan, which cut this function's pixels 300x, barely moved its wall
// clock. The readbacks exist only to FIND a crop rect; the bake itself is one
// cheap drawImage. So the rects are computed here, once, and the runtime skips
// every readback for a covered image.
//
// NO REIMPLEMENTATION. This does not copy the detection algorithm — that is
// how gen_sprite_bbox.mjs earned its dimension guard. It boots the actual game
// in headless Chromium with an empty table, lets the real _lxBakeSeamlessTile
// run its real detection on every tile the game loads, and harvests the rects
// the live code decided on from window._lxTileCropLog. The table IS the
// runtime's own answers. Rows store [w, h, sx, sy, sw, sh]; a [w, h] row
// memoises "detection found nothing" so the miss is not re-paid every boot.
// The runtime rejects a row whose w/h mismatch the loaded image, so redrawn
// art is slow-but-correct until this is re-run.
//
//   node scripts/gen_tile_crops.mjs            # write data/tile_crops.js
//   node scripts/gen_tile_crops.mjs --check    # exit 1 if the table is stale
// ============================================================================
import { chromium } from 'playwright-core';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'data', 'tile_crops.js');
const CHECK = process.argv.includes('--check');
const EXE = [process.env.PW_EXE,
  '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  '/usr/bin/google-chrome', '/usr/bin/chromium',
].find((p) => p && existsSync(p));
if (!EXE) { console.error('no Chromium found'); process.exit(1); }

const free = (p) => new Promise((res) => {
  const sv = createServer().once('error', () => res(false)).once('listening', () => sv.close(() => res(true))).listen(p);
});
let PORT = null;
for (let p = 8920; p <= 8999 && !PORT; p++) if (await free(p)) PORT = String(p);
const srv = spawn(process.execPath, [join(root, 'serve.js'), PORT], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 1200));

const b = await chromium.launch({ executablePath: EXE, headless: true, args: ['--no-sandbox', '--mute-audio'] });
const page = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
// Empty the table BEFORE any game script runs, so every bake takes the live
// detection path and logs its rect — a populated table would harvest nothing.
await page.addInitScript(() => { window.LX_TILE_CROPS = undefined; });
const PAGE = (process.argv.find((a) => a.endsWith(".html"))) || "mojiworld_game.html";
await page.goto(`http://localhost:${PORT}/${PAGE}?dev=1`, { waitUntil: 'domcontentloaded', timeout: 180000 });
await page.waitForFunction(() => typeof game === 'object', null, { timeout: 180000 });
// The tile loaders run at parse time with low fetch priority; give the long
// tail time to land. Settle = the log length stops moving.
let last = -1;
for (let i = 0; i < 40; i++) {
  await page.waitForTimeout(1500);
  const n = await page.evaluate(() => (window._lxTileCropLog || []).length);
  if (n === last && n > 0 && i > 4) break;
  last = n;
}
const log = await page.evaluate(() => window._lxTileCropLog || []);
await b.close();
try { srv.kill(); } catch (e) {}

const T = {};
for (const e of log) {
  let k = e.src || '';
  const o = k.indexOf('/', k.indexOf('//') + 2);
  if (o > 0) k = k.slice(o + 1);
  const q = k.indexOf('?'); if (q >= 0) k = k.slice(0, q);
  try { k = decodeURIComponent(k); } catch (err) {}
  T[k] = e.rect ? [e.w, e.h, ...e.rect] : [e.w, e.h];
}
const keys = Object.keys(T).sort();
const body = '// GENERATED by scripts/gen_tile_crops.mjs — do not hand-edit.\n'
  + '// [w, h, sx, sy, sw, sh] = seamless-tile crop rect for the image at that\n'
  + '// path when its dimensions are exactly w x h; [w, h] = detection found no\n'
  + '// clean tile (memoised null). The runtime falls back to live detection on\n'
  + '// any mismatch, so this can be stale without ever being wrong.\n'
  + 'window.LX_TILE_CROPS = {\n'
  + keys.map((k) => JSON.stringify(k) + ': ' + JSON.stringify(T[k])).join(',\n')
  + '\n};\n';

if (CHECK) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (cur.trim() === body.trim()) { console.log(`data/tile_crops.js is current (${keys.length} rows).`); process.exit(0); }
  console.error('STALE: data/tile_crops.js does not match a fresh harvest. Run: node scripts/gen_tile_crops.mjs');
  process.exit(1);
}
writeFileSync(OUT, body);
console.log(`harvested ${log.length} bakes -> wrote ${keys.length} rows to data/tile_crops.js`);
