// LIVE Gravitos fight profile: a Lv 200 warrior kit-bot pinned beside the boss casting every skill on cooldown, at 1080p.
// Per second: fps / p50 / p95 / max, canvases minted (by creator), DOM mutations. A CDP trace of the middle window is
// aggregated on CrRendererMain BY NAME (never the busiest thread) and on the GPU process main thread; then a JS CPU
// profile names the top self-time functions. Then: paint rects by DOM node, style/layout invalidators (JS stack tops), canvas ops by
// draw group. ABLATE=fn,fn,css:backdrop-off,... alternates base / lever / base windows in one live session (fps ratio per lever);
// CSS='...' applies a stylesheet for the whole run; STUB=fn,fn no-ops functions (both apply once the arena is up).
// Each draw group is also timed (self ms per frame), and every single drawImage over 8 ms is recorded BY SOURCE - which is
// how a freshly minted canvas's texture upload shows itself. CPU=<n> throttles the renderer AFTER the boot, and SWGL=1
// rasterises in software: without one of those this laptop sits on its ~176 fps rAF ceiling and no lever moves the number.
//   [SERVE_ROOT=<root>] [CPU=6] [SWGL=1] FORM=1|3 SECS=12 node scripts/grav_live_profile.mjs [build.html] [out.json]
import { createRequire } from 'node:module'; import path from 'node:path'; import fs from 'node:fs';
import { spawn } from 'node:child_process';
const S = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
// SERVE_ROOT: the directory served (serve.js, data/, art). Default: the repo root when this file lives in scripts/, else ./root next to it.
const ROOT = process.env.SERVE_ROOT || (path.basename(S) === 'scripts' ? path.resolve(S, '..') : path.join(S, 'root')); const require = createRequire(path.join(ROOT, 'x.js'));
const { chromium } = require('playwright-core');
const BUILD = process.argv[2], OUT = process.argv[3] || path.join(S, 'grav_live.json'), PORT = process.env.PORT || '11153';
const FORM = Number(process.env.FORM || 1), SECS = Number(process.env.SECS || 12), VW = Number(process.env.VW || 1920), VH = Number(process.env.VH || 1080);
const env = { ...process.env }; if (BUILD) env.MOJI_GAME_FILE = BUILD; else delete env.MOJI_GAME_FILE;
const server = spawn(process.execPath, [path.join(ROOT, 'serve.js'), PORT], { stdio: 'ignore', cwd: ROOT, env });
await new Promise((r) => setTimeout(r, 1500));
const R = { build: BUILD || 'tip', form: FORM, notes: [] };
const SWGL = process.env.SWGL === '1';   // a software rasteriser stands in for a weak GPU
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: [...(SWGL ? ['--use-angle=swiftshader', '--use-gl=angle', '--disable-gpu-rasterization'] : []), '--mute-audio', '--disable-background-timer-throttling', '--disable-renderer-backgrounding', '--disable-backgrounding-occluded-windows'] });
try {
  const page = await (await browser.newContext({ serviceWorkers: 'block', viewport: { width: VW, height: VH } })).newPage();
  page.on('pageerror', (e) => R.notes.push('pageerror: ' + String(e.message).slice(0, 160)));
  const art404 = []; page.on('response', (r) => { if (r.status() >= 400 && /\/Sprites\//.test(r.url())) art404.push(r.url().split('/Sprites/').pop()); });
  await page.goto(`http://localhost:${PORT}/mojiworld_game.html?dev=1`, { waitUntil: 'domcontentloaded', timeout: 180000 });
  await page.waitForFunction(() => typeof loadMap === 'function' && typeof castSkill === 'function', null, { timeout: 180000 }); await page.waitForTimeout(4000);
  // boot into the arena with a kit; clear every intro / skip overlay until nothing is left; wait for the sprite stream
  const setup = await page.evaluate(async ({ FORM, STUB, CSSX }) => { const sleep = (ms) => new Promise((r2) => setTimeout(r2, ms));
    try { _lxBootGateDone = true; _prologueActive = false; } catch (e) {}
    for (const id of ['loading-overlay', 'lo-auth', 'class-select-modal']) { const el = document.getElementById(id); if (el) el.style.display = 'none'; }
    const master = Object.keys(typeof MASTERS !== 'undefined' ? MASTERS : {}).find((k) => (MASTERS[k].job === 'berserker') || (MASTERS[k].cls === 'warrior')) || null;
    player.cls = 'warrior'; player.job = 'berserker'; player.master = master; player.masteries = master ? { [master]: true } : {}; player.level = 200; player.baseAtk = 3000;
    player._god = true; player.hp = player.maxHp = 999999; player.maxMp = 99999; player.mp = 99999; player.skillCooldowns = player.skillCooldowns || {};
    const kit = Object.keys(SKILLS).filter((id) => { const s = SKILLS[id]; return s.cls === 'warrior' && (!s.job || s.job === player.job) && (!s.master || s.master === player.master); });
    loadMap('gravitosArena'); game.paused = false;
    const clear = () => { let n = 0; for (const id of ['grav-entry-skip', 'boss-intro-skip', 'plg-skip', 'plg-void-skip']) { const b = document.getElementById(id); if (b && b.offsetParent !== null) { b.click(); n++; } }
      for (const id of ['story-beat-overlay', 'boss-intro-overlay']) { const o = document.getElementById(id); if (o && o.classList.contains('on')) { o.classList.remove('on'); n++; } } if (game.paused) { game.paused = false; n++; } return n; };
    let boss = null; for (let i = 0; i < 300 && !boss; i++) { await sleep(100); clear(); boss = game.monsters.find((m) => m && m.type === 'gravitos' && m.currentHp > 0) || null; }
    if (!boss) return { err: 'no gravitos after 30 s' };
    if (FORM === 3) for (let i = 0; i < 2; i++) { const m = game.monsters.find((x) => x && x.type === 'gravitos' && x.currentHp > 0); if (m) { m.evasion = 0; m.currentHp = 1; hitMonster(m, 99999999, false, 'phys'); } for (let j = 0; j < 45; j++) { await sleep(100); clear(); } }
    let quiet = 0; for (let i = 0; i < 200 && quiet < 15; i++) { await sleep(100); quiet = clear() ? 0 : quiet + 1; }
    const t0 = performance.now(); while (performance.now() - t0 < 60000 && (window._lxSpriteDone || 0) < (window._lxSpriteTotal || 0)) { await sleep(200); clear(); }
    // the kit bot
    const cvs = {}; const _ce = document.createElement.bind(document); window.__cvsByCaller = cvs; window.__cvsN = 0;
    document.createElement = function (tag) { if (String(tag).toLowerCase() === 'canvas') { window.__cvsN++; const st = (new Error().stack || '').split('\n').slice(2, 4).map((l) => l.trim().replace(/^at /, '').replace(/ \(.*$/, '').replace(/^.*\//, '')).join(' < '); cvs[st] = (cvs[st] || 0) + 1; } return _ce(tag); };
    window.__mut = 0; window.__mutBy = {}; new MutationObserver((ms) => { window.__mut += ms.length; for (const m of ms) { let a = m.target, idp = ''; for (let i = 0; i < 6 && a; i++, a = a.parentElement) if (a.id) { idp = a.id; break; } const k = (idp || 'body') + '>' + m.target.nodeName + (m.target.className && typeof m.target.className === 'string' ? '.' + m.target.className.split(' ')[0] : '') + ':' + m.type + (m.attributeName ? '.' + m.attributeName : ''); window.__mutBy[k] = (window.__mutBy[k] || 0) + 1; } }).observe(document.documentElement, { childList: true, attributes: true, characterData: true, subtree: true });
    window.__ops = 0; window.__opsBy = {}; { const P = CanvasRenderingContext2D.prototype; for (const fn of ["drawImage", "fillText", "strokeText", "fillRect", "strokeRect", "clearRect", "fill", "stroke", "arc", "beginPath", "save", "restore", "createLinearGradient", "createRadialGradient", "setTransform", "translate", "rotate", "scale", "clip", "measureText", "putImageData", "getImageData"]) { const o = P[fn]; if (typeof o !== "function") continue; P[fn] = function () { window.__ops++; window.__opsBy[fn] = (window.__opsBy[fn] || 0) + 1; const g = window.__grp || "(other)"; const G = window.__opsGrp[g] || (window.__opsGrp[g] = { n: 0 }); G.n++; G[fn] = (G[fn] || 0) + 1; return o.apply(this, arguments); }; } }
    window.__opsGrp = {}; window.__grpMs = {}; for (const fn of "drawBackground,drawAmbient,drawWeather,drawPlatforms,_lxGravArenaDraw,drawPotholes,drawLaunchPads,drawWorldProps,drawChests,drawPowerupOrbs,drawPortals,drawPortalEdgeHints,drawNPCs,drawMemoryEchoes,drawDrops,drawSmoothFx,drawHazards,drawMonster,_drawMobChat,_drawHgWarn,_drawFadingMonsters,_drawAttackZones,drawProjectiles,drawAfterImages,drawDashFx,drawMinions,drawShadowClones,drawSovereignShade,drawBallistaTurrets,_mpDrawPeers,_lxDawnAuraDraw,drawPlayer,drawAegisOrbs,drawNecromancerOrbs,drawHexOrbs,drawPet,drawClassIdentityHUD,drawParticles,drawFxInstances,_lxDeadeyeDraw,drawWorldArtOverlay,drawCalibrationGrid,_lxGravVignetteDraw,drawDamageNumbers,drawIceCheer,_drawControlVignette,_drawPlayerControlOverlay,_drawDayNightTint,drawSuperBossBar,drawTowerSideWalls,drawIcyHud,drawArtPostFX,_lxSafeZoneBeacons,drawMinimap,_drawOffscreenThreats,_lxGravBackdropDraw,_lxGravPulseDraw,drawFlameTrail,_drawTell,drawHUD,_lxDrawBetween,_drawVectorHero,drawSetAura,drawDawnAura,_drawPlayerStatusIcons,_drawPlayerNameTag,_drawPlayerCustomSprite,_drawMsxHero,_drawCuteFaceOverlay,_lxDrawSoft".split(",")) { const o = window[fn]; if (typeof o !== "function") continue; window[fn] = function () { const prev = window.__grp; window.__grp = fn; const _t0 = performance.now(); try { return o.apply(this, arguments); } finally { const _d = performance.now() - _t0; window.__grpMs[fn] = (window.__grpMs[fn] || 0) + _d; if (prev) window.__grpMs[prev] = (window.__grpMs[prev] || 0) - _d; window.__grp = prev; } }; }
    // any single canvas draw over 8 ms, by SOURCE: a lazily-decoded image pays its decode inside the drawImage
    // that first asks for it, and on a slow machine that is a visible hitch mid-fight.
    window.__slowDraw = {};
    { const P = CanvasRenderingContext2D.prototype; const od = P.drawImage;
      P.drawImage = function (im) { const t0 = performance.now(); const r = od.apply(this, arguments); const d = performance.now() - t0;
        if (d > 8) { const src = (im && im.src) ? String(im.src).split('/').slice(-2).join('/') : (im && im.tagName === 'CANVAS' ? 'canvas ' + im.width + 'x' + im.height : (im && im.constructor ? im.constructor.name : '?'));
          const k = src + '  @' + (window.__grp || '(other)'); const o = window.__slowDraw[k] || (window.__slowDraw[k] = { n: 0, ms: 0, max: 0 });
          o.n++; o.ms += d; if (d > o.max) o.max = d; }
        return r; }; }
    window.__casts = 0; window.__bot = true; let lastCast = 0; window.__toasts = {}; if (typeof showToast === "function") { const _st = showToast; window.showToast = function (msg) { const k = String(msg).slice(0, 40); window.__toasts[k] = (window.__toasts[k] || 0) + 1; return _st.apply(this, arguments); }; }
    const tick = () => { if (!window.__bot) return; const m = game.monsters.find((x) => x && x.type === 'gravitos' && x.currentHp > 0); if (m) { player.x = m.x - 170; player.vx = 0; player.facing = 1; if (m.currentHp < m.maxHp * 0.35) m.currentHp = m.maxHp * 0.9; }
      player.hp = 999999; player.mp = 99999; const now = performance.now(); if (now - (window.__lastClear || 0) > 300) { window.__lastClear = now; clear(); }
      if (now - lastCast > 90) { lastCast = now; for (const id of kit) if ((player.skillCooldowns[id] || 0) <= 0 && !(player._skillLockUntil > now)) { try { castSkill(id); window.__casts++; } catch (e) {} } }
      requestAnimationFrame(tick); }; requestAnimationFrame(tick);
    await sleep(3000);
    const blurred = []; for (const el of document.querySelectorAll('body *')) { const cs = getComputedStyle(el); const bf = cs.backdropFilter || cs.webkitBackdropFilter; if (bf && bf !== 'none' && el.getClientRects().length && cs.visibility !== 'hidden' && cs.opacity !== '0') { const r = el.getBoundingClientRect(); if (r.width > 0 && r.height > 0) blurred.push((el.id || el.className && String(el.className).split(' ')[0] || el.tagName) + ' ' + Math.round(r.width) + 'x' + Math.round(r.height) + ' ' + bf); } }
    const anims = {}; try { for (const a of document.getAnimations()) { const el = a.effect && a.effect.target; if (!el) continue; const r = el.getBoundingClientRect(); const k = (a.animationName || a.transitionProperty || a.constructor.name) + ' @ ' + (el.id || (el.className && String(el.className).split(' ').slice(0, 2).join('.')) || el.tagName) + ' ' + Math.round(r.width) + 'x' + Math.round(r.height) + ' ' + (a.effect.getTiming().iterations === Infinity ? 'inf' : 'once') + ' ' + a.playState; anims[k] = (anims[k] || 0) + 1; } } catch (e) { anims.err = String(e); }
    if (CSSX) { const st = document.createElement("style"); st.textContent = CSSX; document.head.appendChild(st); }
    for (const fn of (STUB || "").split(",").filter(Boolean)) { try { window[fn] = function () {}; } catch (e) {} }
    await sleep(400);
    return { htmlClass: document.documentElement.className, noBackdrop: typeof _lxNoBackdropOn !== 'undefined' ? _lxNoBackdropOn : null, statsBf: getComputedStyle(document.getElementById('stats')).backdropFilter, anims, blurred, gameFilter: getComputedStyle(document.getElementById('game')).filter, kit, master, form: boss._gravitosPhase || boss._gravitosForm || boss.phase || null, canvas: canvas.width + 'x' + canvas.height, dpr: typeof _LX_DPR !== 'undefined' ? _LX_DPR : null, quality: (typeof LX_GFX !== 'undefined' && LX_GFX.quality) || null, sprites: (window._lxSpriteDone || 0) + '/' + (window._lxSpriteTotal || 0) };
  }, { FORM, STUB: process.env.STUB || "", CSSX: process.env.CSS || "" });
  // CPU=<n> throttles the renderer AFTER the arena is up, so the fight is measured on a slow machine without
  // making the two-minute boot two-minutes-times-n. The ceiling this laptop hits (~176 fps) hides every lever.
  if (process.env.CPU) { const _c = await page.context().newCDPSession(page); await _c.send('Emulation.setCPUThrottlingRate', { rate: Number(process.env.CPU) }); console.log('cpu throttle x' + process.env.CPU); }
  R.cpu = Number(process.env.CPU || 1); R.swgl = SWGL;
  R.setup = setup; console.log('setup', JSON.stringify(setup)); try { const bc = await browser.newBrowserCDPSession(); const gi = (await bc.send('SystemInfo.getInfo')).gpu || {}; R.gpuInfo = { devices: (gi.devices || []).map((d) => (d.active ? '*' : '') + d.deviceString), renderer: gi.auxAttributes && gi.auxAttributes.gl_renderer, fs: gi.featureStatus }; R.webgl = await page.evaluate(() => { try { const g = document.createElement('canvas').getContext('webgl'); const x = g.getExtension('WEBGL_debug_renderer_info'); return g.getParameter(x.UNMASKED_RENDERER_WEBGL); } catch (e) { return String(e); } }); console.log('gpu', JSON.stringify(R.gpuInfo.devices), R.gpuInfo.renderer, '| webgl:', R.webgl); } catch (e) { R.notes.push('gpuinfo: ' + e.message); } if (setup.err) throw new Error(setup.err);
  if (process.env.ABLATE) {
    const levers = process.env.ABLATE.split(',').filter(Boolean); const WIN = Number(process.env.WIN || 1200), ROUNDS_A = Number(process.env.ROUNDS || 2);
    R.ablate = await page.evaluate(async ({ levers, WIN, ROUNDS_A }) => { const sleep = (ms) => new Promise((r2) => setTimeout(r2, ms));
      const win = async () => { let n = 0, run = true; const f = () => { n++; if (run) requestAnimationFrame(f); }; requestAnimationFrame(f); await sleep(WIN); run = false; return n / (WIN / 1000); };
      const out = {}; const saved = {};
      for (let r = 0; r < ROUNDS_A; r++) for (const fn of levers) {
        const b1 = await win();
        const CSS = { 'css:backdrop-off': '* { backdrop-filter: none !important; -webkit-backdrop-filter: none !important; }', 'css:filter-off': '* { filter: none !important; }', 'css:shadow-off': '* { box-shadow: none !important; text-shadow: none !important; }', 'css:hud-hidden': 'body > *:not(canvas):not(#game-canvas):not(.game-wrapper):not(#gameCanvas) { visibility: hidden !important; } .game-wrapper > *:not(canvas) { visibility: hidden !important; }', 'css:anim-off': '* { animation: none !important; transition: none !important; }' };
        for (const one of fn.split('+')) { if (CSS[one]) { const st = document.createElement('style'); st.textContent = CSS[one]; document.head.appendChild(st); saved[one] = st; continue; } saved[one] = window[one]; window[one] = /Allowed$|Enabled$|Is[A-Z]/.test(one) ? function () { return false; } : function () {}; }
        await sleep(150); const lv = await win();
        for (const one of fn.split('+')) { if (CSS[one]) { saved[one].remove(); continue; } window[one] = saved[one]; }
        await sleep(150); const b2 = await win();
        (out[fn] = out[fn] || []).push({ base: +((b1 + b2) / 2).toFixed(1), lever: +lv.toFixed(1), ratio: +(lv / ((b1 + b2) / 2)).toFixed(3) });
      }
      return out; }, { levers, WIN, ROUNDS_A });
    await page.evaluate(() => { window.__bot = false; });
    const rows = Object.entries(R.ablate).map(([fn, xs]) => { const rs = xs.map((x) => x.ratio).sort((a, b) => a - b); return [fn, rs[rs.length >> 1], xs.map((x) => x.base + '>' + x.lever).join(' ')]; }).sort((a, b) => b[1] - a[1]);
    for (const [fn, med, d] of rows) console.log('  ' + String((med * 100 - 100).toFixed(0) + '%').padStart(6) + '  ' + fn.padEnd(34) + d);
    fs.writeFileSync(OUT, JSON.stringify(R, null, 1)); await browser.close().catch(() => {}); server.kill(); process.exit(0);
  }
  // per-second frame series while the fight runs
  const series = page.evaluate(async (SECS) => { const out = []; const t0 = performance.now(); let last = t0, cur = [], sec = 0, c0 = window.__cvsN, m0 = window.__mut, k0 = window.__casts, o0 = window.__ops; window.__opsBy = {}; window.__opsGrp = {}; window.__grpMs = {}; const f0 = { n: 0 };
    await new Promise((done) => { const f = (t) => { cur.push(t - last); last = t; if (t - t0 >= (sec + 1) * 1000) { cur.sort((a, b) => a - b); out.push({ s: sec, fps: cur.length, p50: +cur[cur.length >> 1].toFixed(1), p95: +cur[Math.floor(cur.length * 0.95)].toFixed(1), max: +cur[cur.length - 1].toFixed(1), cvs: window.__cvsN - c0, mut: window.__mut - m0, casts: window.__casts - k0, opsPerFrame: Math.round((window.__ops - o0) / cur.length), low: LX_PERF.lowFx ? 1 : 0, vlow: LX_PERF.veryLowFx ? 1 : 0, rs: +(canvas.width / innerWidth).toFixed(2) }); c0 = window.__cvsN; m0 = window.__mut; k0 = window.__casts; o0 = window.__ops; f0.n += cur.length; cur = []; sec++; }
      if (t - t0 < SECS * 1000) requestAnimationFrame(f); else done(); }; requestAnimationFrame(f); });
    window.__opsFrames = f0.n; return out; }, SECS);
  // trace the middle of it on the renderer main thread and the GPU main thread
  const cdp = await page.context().newCDPSession(page); const events = []; cdp.on('Tracing.dataCollected', (e) => { for (const ev of e.value) events.push(ev); });
  await new Promise((r) => setTimeout(r, 2000));
  await cdp.send('Tracing.start', { categories: 'toplevel,devtools.timeline,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,disabled-by-default-v8.gc,v8.execute,blink,v8,gpu,cc,disabled-by-default-devtools.timeline.stack,disabled-by-default-devtools.timeline.invalidationTracking,disabled-by-default-blink.invalidation', transferMode: 'ReportEvents' });
  await new Promise((r) => setTimeout(r, Math.max(4000, (SECS - 4) * 1000)));
  await cdp.send('Tracing.end'); await new Promise((r) => cdp.once('Tracing.tracingComplete', r));
  R.series = await series; R.cvsByCaller = await page.evaluate(() => Object.entries(window.__cvsByCaller).sort((a, b) => b[1] - a[1]).slice(0, 12));
  R.mutBy = await page.evaluate(() => Object.entries(window.__mutBy).sort((a, b) => b[1] - a[1]).slice(0, 14)); R.opsBy = await page.evaluate(() => Object.entries(window.__opsBy).map(([k, v]) => [k, +(v / Math.max(1, window.__opsFrames)).toFixed(1)]).sort((a, b) => b[1] - a[1])); R.opsGrp = await page.evaluate(() => Object.entries(window.__opsGrp).map(([g, o]) => [g, +(o.n / Math.max(1, window.__opsFrames)).toFixed(1), Object.entries(o).filter(([k]) => k !== 'n').sort((a, b) => b[1] - a[1]).slice(0, 5).map(([k, v]) => k + ' ' + (v / Math.max(1, window.__opsFrames)).toFixed(1)).join(', ')]).sort((a, b) => b[1] - a[1]).slice(0, 18)); R.slowDraw = await page.evaluate(() => Object.entries(window.__slowDraw || {}).map(([k, o]) => [k, o.n, +o.ms.toFixed(0), +o.max.toFixed(0)]).sort((a, b) => b[2] - a[2]).slice(0, 14)); R.grpMs = await page.evaluate(() => Object.entries(window.__grpMs || {}).map(([g, ms]) => [g, +(ms / Math.max(1, window.__opsFrames)).toFixed(3)]).sort((a, b) => b[1] - a[1]).slice(0, 22)); R.toasts = await page.evaluate(() => Object.entries(window.__toasts || {}).sort((a, b) => b[1] - a[1]).slice(0, 8));
  // JS CPU profile: top self-time functions
  await cdp.send('Profiler.enable'); await cdp.send('Profiler.setSamplingInterval', { interval: 200 }); await cdp.send('Profiler.start');
  await new Promise((r) => setTimeout(r, 6000)); const { profile } = await cdp.send('Profiler.stop');
  { const byId = new Map(); for (const n of profile.nodes) byId.set(n.id, n); const self = new Map(); let tot = 0; const d = profile.timeDeltas || [], sm = profile.samples || [];
    for (let i = 0; i < sm.length; i++) { const x = (d[i] || 0) / 1000; tot += x; self.set(sm[i], (self.get(sm[i]) || 0) + x); }
    R.js = { totalMs: Math.round(tot), top: [...self.entries()].map(([id, ms]) => { const f = (byId.get(id) || {}).callFrame || {}; return [Math.round(ms), f.functionName || '(anon)', (f.lineNumber || 0) + 1]; }).sort((a, b) => b[0] - a[0]).slice(0, 28) }; }
  await page.evaluate(() => { window.__bot = false; });
  R.art404 = art404.slice(0, 5);
  try { const X0 = events.filter((e) => e.ph === 'X' && e.dur > 0 && e.name === 'Paint' && e.args && e.args.data && e.args.data.clip); const byNode = {}; for (const e of X0) { const c = e.args.data.clip; const w = Math.round(Math.abs(c[2] - c[0])), h = Math.round(Math.abs(c[5] - c[1])); const size = w > 1e6 ? 'unbounded' : w + 'x' + h; const k = e.args.data.nodeId + '|' + size; const o = byNode[k] || (byNode[k] = { n: 0, nodeId: e.args.data.nodeId, size, px: w > 1e6 ? 0 : w * h }); o.n++; } const all = Object.values(byNode); const pick = [].concat(all.filter((o) => o.size === 'unbounded').sort((a, b) => b.n - a.n).slice(0, 4), all.filter((o) => o.px >= 500000).sort((a, b) => b.n - a.n).slice(0, 5), all.filter((o) => o.px > 0 && o.px < 500000).sort((a, b) => b.n * b.px - a.n * a.px).slice(0, 6)); const names = {}; for (const o of pick) { if (names[o.nodeId] !== undefined) continue; try { const { object } = await cdp.send('DOM.resolveNode', { backendNodeId: o.nodeId }); const r = await cdp.send('Runtime.callFunctionOn', { objectId: object.objectId, functionDeclaration: 'function () { const d = (el) => el && el.nodeType === 1 ? el.tagName.toLowerCase() + (el.id ? "#" + el.id : "") + (el.className && typeof el.className === "string" ? "." + el.className.trim().split(/s+/).slice(0, 2).join(".") : "") : String(el && el.nodeName); return d(this) + " < " + d(this.parentElement) + " < " + d(this.parentElement && this.parentElement.parentElement); }', returnByValue: true }); names[o.nodeId] = r.result.value; } catch (e) { names[o.nodeId] = 'node ' + o.nodeId + ' (' + String(e.message).slice(0, 50) + ')'; } } R.paintNodes = pick.map((o) => [o.size, o.n, names[o.nodeId]]); } catch (e) { R.notes.push('paintNodes: ' + e.message); }
  // aggregate the trace
  const X = events.filter((e) => e.ph === 'X' && e.dur > 0); const names = events.filter((e) => e.ph === 'M' && e.name === 'thread_name');
  const byName = (nm) => { const ks = names.filter((e) => e.args && e.args.name === nm).map((e) => e.pid + ':' + e.tid); const load = new Map(); for (const e of X) { const k = e.pid + ':' + e.tid; if (ks.includes(k)) load.set(k, (load.get(k) || 0) + e.dur); } const top = [...load.entries()].sort((a, b) => b[1] - a[1])[0]; return top ? top[0] : null; };
  const agg = (key) => { if (!key) return null; const [p, t] = key.split(':').map(Number); const M = X.filter((e) => e.pid === p && e.tid === t).sort((a, b) => a.ts - b.ts); const span = M.length ? (M[M.length - 1].ts + M[M.length - 1].dur - M[0].ts) / 1000 : 1;
    const tot = new Map(); for (const e of M) if (!/RunTask$/.test(e.name)) tot.set(e.name, (tot.get(e.name) || 0) + e.dur);
    const tasks = M.filter((e) => /RunTask$/.test(e.name)); const busy = tasks.reduce((s, e) => s + e.dur, 0);
    const long = tasks.filter((e) => e.dur >= 12000).sort((a, b) => b.dur - a.dur).slice(0, 6).map((tk) => { const inner = new Map(); for (const e of M) { if (e === tk || /RunTask$/.test(e.name)) continue; if (e.ts >= tk.ts && e.ts + e.dur <= tk.ts + tk.dur) inner.set(e.name, (inner.get(e.name) || 0) + e.dur); } return [+(tk.dur / 1000).toFixed(1), [...inner.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5).map(([n, d]) => n + ' ' + (d / 1000).toFixed(1)).join(', ')]; });
    return { spanMs: Math.round(span), busyPct: +(busy / 10 / span).toFixed(1), longTasks: tasks.filter((e) => e.dur >= 12000).length, top: [...tot.entries()].sort((a, b) => b[1] - a[1]).slice(0, 24).map(([n, d]) => [+(d / 1000).toFixed(1), n]), longest: long }; };
  { const inv = {}; const pinv = {}; for (const e of events) { if (e.name === 'ScheduleStyleRecalculation' || e.name === 'InvalidateLayout') { const st = (e.args && e.args.data && e.args.data.stackTrace) || []; const top = st.slice(0, 3).map((f) => (f.functionName || '(anon)') + ':' + (f.lineNumber + 1)).join(' < '); const k = e.name + ' :: ' + top; inv[k] = (inv[k] || 0) + 1; } if (e.name === 'PaintInvalidationTracking' || e.name === 'StyleInvalidatorInvalidationTracking' || e.name === 'StyleRecalcInvalidationTracking' || e.name === 'LayoutInvalidationTracking') { const d = (e.args && e.args.data) || {}; const k = e.name + ' :: ' + (d.reason || '') + ' ' + (d.nodeName || '') + ' ' + (d.selectorPart || d.changedClass || d.changedAttribute || d.changedId || '') + (d.stackTrace ? ' @ ' + ((d.stackTrace[0] || {}).functionName || '') + ':' + ((d.stackTrace[0] || {}).lineNumber + 1) : ''); pinv[k] = (pinv[k] || 0) + 1; } } R.invalidators = Object.entries(inv).sort((a, b) => b[1] - a[1]).slice(0, 16); R.invTracking = Object.entries(pinv).sort((a, b) => b[1] - a[1]).slice(0, 16); const paintInv = {}; for (const e of events) { if (e.name !== 'PaintInvalidationTracking' && e.name !== 'LayoutObjectInvalidationTracking' && e.name !== 'PaintInvalidation') continue; const d = (e.args && e.args.data) || {}; const k = e.name + ' :: ' + (d.reason || '') + ' | ' + (d.nodeName || '') + ' | ' + (d.selectorPart || d.changedClass || d.changedAttribute || d.changedId || '') + (d.clientRect ? ' ' + d.clientRect.map(Math.round).join(',') : ''); paintInv[k] = (paintInv[k] || 0) + 1; } R.paintInv = Object.entries(paintInv).sort((a, b) => b[1] - a[1]).slice(0, 18); }
  { const dec = {}; for (const e of events) { if (!/Decode|PaintImage|ImageDecode/.test(e.name)) continue; const d = (e.args && (e.args.data || e.args)) || {}; const u = d.imageUrl || d.url || d.src || ''; const k = e.name + ' :: ' + (u ? String(u).split('/').slice(-2).join('/') : (d.srcWidth ? d.srcWidth + 'x' + d.srcHeight : JSON.stringify(d).slice(0, 70))); const o = dec[k] || (dec[k] = { n: 0, ms: 0 }); o.n++; o.ms += (e.dur || 0) / 1000; } R.decodes = Object.entries(dec).map(([k, o]) => [k, o.n, +o.ms.toFixed(1)]).sort((a, b) => b[2] - a[2]).slice(0, 16); }
  R.main = agg(byName('CrRendererMain')); R.gpu = agg(byName('CrGpuMain'));
  { const mk = byName('CrRendererMain'); const [p, t] = mk ? mk.split(':').map(Number) : [0, 0]; const paints = X.filter((e) => e.pid === p && e.tid === t && e.name === 'Paint' && e.args && e.args.data && e.args.data.clip); const by = {}; for (const e of paints) { const c = e.args.data.clip; const w = Math.abs(c[2] - c[0]), h = Math.abs(c[5] - c[1]); const k = 'layer ' + e.args.data.layerId + ' ' + Math.round(w) + 'x' + Math.round(h); const o = by[k] || (by[k] = { n: 0, ms: 0, area: 0 }); o.n++; o.ms += e.dur / 1000; o.area += w * h; } const frames = Math.max(1, X.filter((e) => e.pid === p && e.tid === t && e.name === 'FireAnimationFrame').length); R.paintFrames = frames; R.paints = Object.entries(by).map(([k, o]) => [k, o.n, +(o.n / frames).toFixed(2), +(o.ms).toFixed(1), Math.round(o.area / frames / 1000)]).sort((a, b) => b[4] - a[4]).slice(0, 14); }
} catch (e) { R.fatal = String(e.stack || e).split('\n').slice(0, 3).join(' | '); console.log('FATAL', R.fatal); }
await browser.close().catch(() => {}); server.kill();
fs.writeFileSync(OUT, JSON.stringify(R, null, 1));
const s = R.series || []; const fps = s.map((x) => x.fps), p95 = s.map((x) => x.p95);
console.log(`series: fps ${fps.join(' ')}\n  p95 ${p95.join(' ')}\n  cvs ${s.map((x) => x.cvs).join(' ')}  mut ${s.map((x) => x.mut).join(' ')}  casts ${s.map((x) => x.casts).join(' ')}  low/vlow ${s.map((x) => x.low + '' + x.vlow).join(' ')}  rs ${s.map((x) => x.rs).join(' ')}`);
if (R.main) { console.log(`main: busy ${R.main.busyPct}% of ${R.main.spanMs} ms, long tasks ${R.main.longTasks}`); for (const [d, n] of R.main.top) console.log('  ' + String(d).padStart(8) + ' ms  ' + n); for (const l of R.main.longest) console.log('  long ' + l[0] + ' ms :: ' + l[1]); }
if (R.gpu) { console.log(`gpu main: busy ${R.gpu.busyPct}% of ${R.gpu.spanMs} ms`); for (const [d, n] of R.gpu.top.slice(0, 8)) console.log('  ' + String(d).padStart(8) + ' ms  ' + n); }
if (R.js) { console.log('js self-time top (' + R.js.totalMs + ' ms sampled):'); for (const r of R.js.top) if (r[0] >= 4) console.log('  ' + String(r[0]).padStart(6) + ' ms  ' + r[1] + ' :' + r[2]); }
console.log('style/layout invalidators (JS stack top):'); for (const [k, n] of (R.invalidators || [])) console.log('  ' + String(n).padStart(6) + '  ' + k); console.log('invalidation tracking:'); for (const [k, n] of (R.invTracking || [])) console.log('  ' + String(n).padStart(6) + '  ' + k); console.log('paint invalidation tracking:'); for (const [k, n] of (R.paintInv || [])) console.log('  ' + String(n).padStart(6) + '  ' + k); console.log('paint rects by DOM node [node, size, paints]:'); for (const r of (R.paintNodes || [])) console.log('  ' + JSON.stringify(r)); console.log('DOM paints over ' + R.paintFrames + ' frames [layer size, paints, paints/frame, ms, kpx/frame]:'); for (const r of (R.paints || [])) console.log('  ' + JSON.stringify(r)); console.log('single draws over 8 ms [source @ group, count, total ms, worst ms]:'); for (const r of (R.slowDraw || [])) console.log('  ' + JSON.stringify(r)); console.log('image decode in the traced window [what, count, ms]:'); for (const r of (R.decodes || [])) console.log('  ' + JSON.stringify(r)); console.log('canvases by caller', JSON.stringify(R.cvsByCaller)); console.log('toasts', JSON.stringify(R.toasts)); console.log('ops/frame', s.map((x) => x.opsPerFrame).join(' '), 'by method', JSON.stringify(R.opsBy)); console.log('ms/frame by draw group (self time):'); for (const [g, ms] of (R.grpMs || [])) if (ms >= 0.01) console.log('  ' + String(ms.toFixed(3)).padStart(7) + '  ' + g); console.log('ops/frame by draw group:'); for (const [g, n, d] of (R.opsGrp || [])) console.log('  ' + String(n).padStart(7) + '  ' + g.padEnd(26) + d); console.log('mutations by target', JSON.stringify(R.mutBy)); console.log('art404', JSON.stringify(R.art404), 'notes', JSON.stringify(R.notes.slice(0, 4)));
