// A MAP SPAWNS ONLY ITS OWN ROSTER.
// =============================================================================
// Per user (v0.29.635): "the monsters should be fixed per map, it should not
// have monsters within the tiers joining, the monsters currently in it should
// be the only ones in the map."
//
// What this guards against is a real, shipped bug: loadMap used to end with an
// 8%-per-load roll that added one mob from OUTSIDE the map's spawn table. It
// put a Lv 44 Spook (1642 HP, 253 ATK, flying) in the Lv 1-4 starter forest and
// a Lv 15 Pincer among Stardust Atrium's Lv 47 residents. Bounding it to the
// map's tier was tried first and rejected; the roll is now gone.
//
// A. STATIC: no wanderer-shaped code may come back.
// B. LIVE:   load every combat map repeatedly and assert every monster present
//            is a type the map itself declares.
// C. CONTROL: the same sweep MUST report violations on a build that still has
//            the roll, otherwise a test that spawns nothing would also "pass".
//            The control build is generated by re-inserting the roll into a
//            scratch copy, so it does not depend on git history staying put.
//
// Run: node scripts/map_roster_test.mjs   (MOJI_GAME_FILE overrides)
import { createRequire } from 'node:module';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const { chromium } = require('playwright-core');
const FILE = process.env.MOJI_GAME_FILE || 'mojiworld_game.html';
const REPS = +(process.env.MOJI_ROSTER_REPS || 12);
const res = [];
const ok = (n, c, extra) => res.push({ n, pass: !!c, extra: extra === undefined ? '' : String(extra) });

const SRC = fs.readFileSync(path.join(ROOT, FILE), 'utf8');

// ── A. STATIC ────────────────────────────────────────────────────────────────
ok('no hardcoded wanderer list', !/const wanderers\s*=/.test(SRC));
ok('no wanderer pool builder', !/_lxWandererPool|_LX_WANDER_POOL/.test(SRC));
ok('no out-of-table spawn behind the 8% roll',
   !/Math\.random\(\) < 0\.08[\s\S]{0,400}spawnFromMap\(pick/.test(SRC));

// ── the sweep, run identically against any served file ───────────────────────
const SWEEP = (reps) => {
  const out = { maps: 0, loads: 0, monsters: 0, violations: 0, violatingMaps: 0, sample: [] };
  for (const id in MAPS) {                                      // eslint-disable-line no-undef
    const md = MAPS[id];                                        // eslint-disable-line no-undef
    if (!md || md.isTown || md.isBossArena || md.isTower) continue;
    const allowed = new Set((md.spawns || []).filter(s => s && s.type).map(s => s.type));
    out.maps++;
    let bad = false;
    for (let i = 0; i < reps; i++) {
      try { loadMap(id); } catch (e) { continue; }              // eslint-disable-line no-undef
      out.loads++;
      for (const m of game.monsters) {                          // eslint-disable-line no-undef
        out.monsters++;
        if (m.ally || m.isSummon || m._playerOwned) continue;
        if (!allowed.has(m.type)) {
          out.violations++; bad = true;
          if (out.sample.length < 10) out.sample.push(`${id}:${m.type}`);
        }
      }
    }
    if (bad) out.violatingMaps++;
  }
  return out;
};

// ── the control build: same file, with the roll put back ─────────────────────
const CONTROL = path.join(os.tmpdir(), `_moji_roster_control_${process.pid}.html`);
{
  const anchor = 'function spawnChest(x, y, tier) {';
  if (SRC.split(anchor).length - 1 !== 1) throw new Error('control anchor not unique');
  // Re-create the removed behaviour verbatim, exposed so the sweep can trip it.
  const revived = `
function _lxTestWanderer() {
  if (!game.mapData || game.mapData.isTown || game.mapData.isBossArena || game.mapData.isTower) return;
  const wanderers = ['slime','mushroom','horny','stump','scorpion','wraith'];
  spawnFromMap(wanderers[Math.floor(Math.random() * wanderers.length)], false);
}
const _lxRealLoadMap = loadMap;
loadMap = function (id, ex, ey) {
  const r = _lxRealLoadMap.apply(this, arguments);
  if (Math.random() < 0.08) { try { _lxTestWanderer(); } catch (e) {} }
  return r;
};
${anchor}`;
  fs.writeFileSync(CONTROL, SRC.replace(anchor, revived), 'utf8');
}

// ── B / C. LIVE ──────────────────────────────────────────────────────────────
const PORT = 9121;
const server = spawn(process.execPath, [path.join(ROOT, 'serve.js'), String(PORT)], { stdio: 'ignore' });
await new Promise(r => setTimeout(r, 1200));
const browser = await chromium.launch({
  channel: process.env.MOJI_PW_EXE ? undefined : 'msedge',
  executablePath: process.env.MOJI_PW_EXE || undefined,
  headless: true,
});
const errs = [];

const run = async (url) => {
  const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
  page.on('pageerror', e => errs.push(String(e).slice(0, 200)));
  await page.goto(url, { waitUntil: 'load', timeout: 60000 });
  await page.waitForTimeout(10000);
  await page.evaluate(() => {
    for (const id of ['class-select-modal', 'advancement-modal', 'tutorial-modal', 'loading-overlay']) {
      const el = document.getElementById(id); if (el) el.style.display = 'none';
    }
  });
  const r = await page.evaluate(SWEEP, REPS);
  await page.close();
  return r;
};

const live = await run(`http://localhost:${PORT}/${FILE}`);
ok('every monster on every combat map is one the map declares',
   live.violations === 0,
   `${live.maps} maps x ${REPS} loads = ${live.loads} loads, ${live.monsters} monsters, ` +
   `${live.violations} violations${live.sample.length ? ' — ' + live.sample.join(' | ') : ''}`);
ok('the sweep actually saw monsters (not a vacuous pass)',
   live.monsters > 1000, `${live.monsters} monsters observed`);

// Serve the control from the temp dir via a file:// URL — no need to copy it
// into the repo, and nothing to clean up inside the working tree.
const control = await run('file:///' + CONTROL.replace(/\\/g, '/'));
ok('CONTROL: the same sweep DOES catch a build with the wanderer put back',
   control.violations > 0,
   `${control.violations} violations across ${control.violatingMaps} maps` +
   `${control.sample.length ? ' — ' + control.sample.slice(0, 5).join(' | ') : ''}`);

await browser.close();
server.kill();
try { fs.unlinkSync(CONTROL); } catch (e) {}

for (const r of res) console.log(`  ${r.pass ? 'PASS' : 'FAIL'}  ${r.n}${r.extra ? '  (' + r.extra + ')' : ''}`);
const failed = res.filter(r => !r.pass).length;
console.log(`${res.length - failed} passed, ${failed} failed`);
console.log('pageerrors:', errs.length, errs.slice(0, 3));
process.exit(failed ? 1 : 0);
