import { chromium } from 'playwright-core';
const EXE = process.env.PW_EXE || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const URL = 'file:///home/user/Mojiworld/tools/map_editor.html';
const OUT = '/tmp/claude-0/-home-user-Mojiworld/1652515c-62db-56d2-8863-1459f775405a/scratchpad';
const b = await chromium.launch({ executablePath: EXE, headless: true, args: ['--no-sandbox', '--disable-gpu'] });
const p = await b.newContext({ viewport: { width: 1360, height: 800 } }).then(c => c.newPage());
await p.goto(URL, { waitUntil: 'load' });
await p.waitForFunction(() => typeof state === 'object' && state.npcs);
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + '/editor_main.png' });
await p.click('#worldMapBtn');
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + '/editor_worldmap.png' });
await b.close();
console.log('shots saved');
