#!/usr/bin/env node
// Packs every generated emoji icon (Sprites/ui/emoji/<cp>.webp) into one atlas
// image and writes the lookup the game reads.
// ============================================================================
// One image, one request, and a single drawImage source rect per glyph on the
// canvas side (CSS background-position on the DOM side), instead of ~400 files.
//   Sprites/ui/emoji_atlas.webp   CELL x CELL tiles, COLS per row, transparent
//   data/emoji_atlas.js           window.LX_EMOJI_ATLAS = { v, src, cell, cols,
//                                   rows, map: { '<cp>': index } }
// <cp> is the emoji's code points in lower-case hex joined by '-', with
// variation selectors (FE0E/FE0F) and skin tones removed - the key the runtime
// computes for any form of the same emoji.
//   node scripts/pack_emoji_atlas.mjs [--cell=64] [--cols=24]
import { readdirSync, writeFileSync, renameSync, statSync } from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const sharp = require('sharp'); sharp.cache(false);
const arg = (k, d) => { const a = process.argv.find((x) => x.startsWith('--' + k + '=')); return a ? a.slice(k.length + 3) : d; };
const CELL = Number(arg('cell', 64)), COLS = Number(arg('cols', 24));
const SRC_DIR = path.join(ROOT, 'Sprites/ui/emoji');
const ids = readdirSync(SRC_DIR).filter((f) => /^[0-9a-f]+(-[0-9a-f]+)*\.webp$/.test(f)).map((f) => f.slice(0, -5)).sort();
if (!ids.length) { console.error('no icons in ' + SRC_DIR); process.exit(1); }
const ROWS = Math.ceil(ids.length / COLS);
const tiles = [];
for (let i = 0; i < ids.length; i++) {
  const buf = await sharp(path.join(SRC_DIR, ids[i] + '.webp')).resize(CELL, CELL, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toBuffer();
  tiles.push({ input: buf, left: (i % COLS) * CELL, top: Math.floor(i / COLS) * CELL });
}
const OUT_IMG = path.join(ROOT, 'Sprites/ui/emoji_atlas.webp');
await sharp({ create: { width: COLS * CELL, height: ROWS * CELL, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
  .composite(tiles).webp({ quality: 88, alphaQuality: 100, effort: 6 }).toFile(OUT_IMG + '.tmp.webp');
renameSync(OUT_IMG + '.tmp.webp', OUT_IMG);
const map = {}; ids.forEach((id, i) => { map[id] = i; });
const v = Date.now().toString(36);
const js = `// Generated by scripts/pack_emoji_atlas.mjs - do not edit by hand.\n`
  + `// Custom ludo.ai icons that replace every emoji the game draws (see _lxEmoji* in mojiworld_game.html).\n`
  + `window.LX_EMOJI_ATLAS = ${JSON.stringify({ v, src: 'Sprites/ui/emoji_atlas.webp?v=' + v, cell: CELL, cols: COLS, rows: ROWS, map })};\n`;
const OUT_JS = path.join(ROOT, 'data/emoji_atlas.js');
writeFileSync(OUT_JS + '.tmp', js); renameSync(OUT_JS + '.tmp', OUT_JS);
console.log(`atlas: ${ids.length} icons, ${COLS}x${ROWS} cells of ${CELL}px -> ${path.relative(ROOT, OUT_IMG)} (${Math.round(statSync(OUT_IMG).size / 1024)} KB); map -> data/emoji_atlas.js`);
