// Test: the precomputed sprite-bbox table is EQUIVALENT to the live pixel scan
// it replaces, and the runtime actually uses it.
//
// This matters more than a normal perf test: bbox is what plants a sprite's
// feet on the floor line. A wrong number does not crash anything — it silently
// floats or sinks a monster, which is exactly the kind of regression a perf
// change is expected to sneak in. So the table is graded against the real scan,
// in the browser, on the shipped art.
//   node scripts/sprite_bbox_test.mjs [build.html]
import { chromium } from 'playwright-core';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
const ROOT = 'C:/Users/dpeh0/Mojiworld';
const results = []; const ok = (n, c, x) => results.push({ n, pass: !!c, x });

ok('the generated table ships', existsSync(path.join(ROOT, 'data/sprite_bbox.js')), '');
const raw = readFileSync(path.join(ROOT, 'data/sprite_bbox.js'), 'utf8');
ok('it is marked generated (no hand-edits invited)', /GENERATED by scripts\/gen_sprite_bbox\.mjs/.test(raw), '');
const entries = (raw.match(/":"/g) || []).length;
ok('it covers the sprite trees that get scanned (>3000 entries)', entries > 3000, { entries });

const PORT = process.env.PERF_PORT || '9501';
const srv = spawn(process.execPath, [path.join(ROOT, 'serve.js'), PORT], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 1500));
const GAME = process.argv[2] || 'mojiworld_game.html';
const browser = await chromium.launch({ channel: 'chrome', args: ['--disable-background-timer-throttling'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const errs = []; page.on('pageerror', (e) => errs.push(String(e).slice(0, 160)));
await page.goto(`http://localhost:${PORT}/${GAME}?dev=1`, { waitUntil: 'domcontentloaded' });
await page.waitForFunction(() => typeof _detectSpriteBboxBottom === 'function', { timeout: 120000 });

const r = await page.evaluate(async () => {
  const out = { checked: 0, mismatches: [], tableSize: 0, usedTable: 0 };
  out.tableSize = Object.keys(window.LX_SPRITE_BBOX || {}).length;
  // The live scan, verbatim, so the comparison is against the real thing and
  // not against a re-implementation that could share a bug with the table.
  const liveBottom = (img) => {
    const cv = document.createElement('canvas');
    cv.width = img.naturalWidth; cv.height = img.naturalHeight;
    const c = cv.getContext('2d', { willReadFrequently: true });
    c.drawImage(img, 0, 0);
    const d = c.getImageData(0, 0, cv.width, cv.height).data;
    for (let y = cv.height - 1; y >= 0; y--) {
      let run = 0;
      for (let x = 0; x < cv.width; x++) {
        if (d[(y * cv.width + x) * 4 + 3] > 64) { if (++run >= 2) return y; } else run = 0;
      }
    }
    return cv.height - 1;
  };
  const liveTop = (img) => {
    const cv = document.createElement('canvas');
    cv.width = img.naturalWidth; cv.height = img.naturalHeight;
    const c = cv.getContext('2d', { willReadFrequently: true });
    c.drawImage(img, 0, 0);
    const d = c.getImageData(0, 0, cv.width, cv.height).data;
    for (let y = 0; y < cv.height; y++) {
      for (let x = 0; x < cv.width; x++) if (d[(y * cv.width + x) * 4 + 3] > 12) return y;
    }
    return 0;
  };
  const load = (src) => new Promise((res) => {
    const im = new Image(); im.onload = () => res(im); im.onerror = () => res(null); im.src = src;
  });
  // A spread across the trees rather than the first N of one folder.
  const keys = Object.keys(window.LX_SPRITE_BBOX || {});
  const step = Math.max(1, Math.floor(keys.length / 40));
  for (let i = 0; i < keys.length && out.checked < 40; i += step) {
    const k = keys[i];
    const img = await load('Sprites/' + k);
    if (!img || !img.naturalWidth) continue;
    const row = window.LX_SPRITE_BBOX[k].split(',').map(Number);
    const lb = liveBottom(img), lt = liveTop(img);
    out.checked++;
    if (lb !== row[1] || lt !== row[0]) out.mismatches.push({ k, table: [row[0], row[1]], live: [lt, lb] });
    // and the runtime path must return the same value
    if (_detectSpriteBboxBottom(img) === row[1]) out.usedTable++;
  }
  return out;
});
ok('the runtime loaded the table', r.tableSize > 3000, { tableSize: r.tableSize });
ok(`table matches a live pixel scan on every sampled sprite (${r.checked} sampled)`,
   r.checked >= 20 && r.mismatches.length === 0, r.mismatches.slice(0, 4));
ok('the runtime scanner returns the table value', r.usedTable === r.checked, { agreed: r.usedTable, of: r.checked });
ok('no page errors', errs.length === 0, errs.slice(0, 3));

for (const q of results) console.log((q.pass ? 'PASS ' : 'FAIL ') + ' ' + q.n + '  ' + JSON.stringify(q.x ?? ''));
console.log(`${results.filter((q) => q.pass).length}/${results.length} checks passed`);
await browser.close(); srv.kill();
process.exit(results.every((q) => q.pass) ? 0 : 1);
