// THE TOWER BOSSES MOVE (final polish audit R10; per user "Work on all the above"). The Arbiter's VERDICT and column and the
// Sovereign's volley were near-static sets (a pose held for nine frames while only a flame flickered). Regenerated by
// scripts/gen_tower_anim_ludo.mjs; this pins what the regen promised: nine frames on the set's own canvas, frame 0 at the
// shipped size and foot line (so the calibration still fits), and real motion - mean frame-to-frame change over the
// character's region, which the old sets fall well short of (0.97 / 3.58 / 4.60).
//   node scripts/tower_anim_motion_test.mjs
import sharp from 'sharp';
import path from 'node:path'; import { existsSync } from 'node:fs'; import { fileURLToPath } from 'node:url';
sharp.cache(false);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let pass = 0, fail = 0; const check = (ok, msg, d) => { console.log((ok ? 'PASS ' : 'FAIL ') + msg + (d !== undefined ? '  [' + JSON.stringify(d) + ']' : '')); ok ? pass++ : fail++; };
const SETS = {
  towerArbiterverdict:  { canvas: [1500, 1300], h: 550, bottom: 1300, cx: 651, region: { x: 153, y: 337, s: 996 }, minMotion: 2.5 },
  towerArbitercolumn:   { canvas: [1500, 1300], h: 358, bottom: 1298, cx: 674, region: { x: 347, y: 665, s: 654 }, minMotion: 6 },
  towerSovereignvolley: { canvas: [1656, 1314], h: 426, bottom: 1299, cx: 916, region: { x: 514, y: 522, s: 803 }, minMotion: 5 },
};
for (const [set, S] of Object.entries(SETS)) {
  const files = [...Array(9).keys()].map((i) => path.join(ROOT, 'Sprites', 'bosses', 'attack', `${set}_${i}.webp`));
  const have = files.filter((f) => existsSync(f)).length;
  check(have === 9, `${set}: nine frames`, have);
  if (have !== 9) continue;
  const md = await Promise.all(files.map((f) => sharp(f).metadata()));
  check(md.every((m) => m.width === S.canvas[0] && m.height === S.canvas[1]), `${set}: every frame on the ${S.canvas.join('x')} canvas`, md.map((m) => m.width + 'x' + m.height)[0]);
  const t = await sharp(files[0]).trim({ threshold: 8 }).toBuffer({ resolveWithObject: true });
  const h = t.info.height, bottom = -t.info.trimOffsetTop + h, cx = -t.info.trimOffsetLeft + t.info.width / 2;
  check(Math.abs(h - S.h) / S.h <= 0.03 && Math.abs(bottom - S.bottom) <= 3 && Math.abs(cx - S.cx) <= 6,
    `${set}: frame 0 keeps the shipped size, foot line and centre`, { h, bottom, cx: Math.round(cx) });
  const reg = { left: Math.max(0, S.region.x), top: Math.max(0, S.region.y) };
  reg.width = Math.min(S.canvas[0] - reg.left, S.region.s); reg.height = Math.min(S.canvas[1] - reg.top, S.region.s);
  const px = await Promise.all(files.map(async (f) => (await sharp(f).extract(reg).resize(256, 256, { fit: 'fill' }).flatten({ background: '#808080' }).removeAlpha().raw().toBuffer())));
  let tot = 0;
  for (let i = 0; i < 9; i++) { const a = px[i], b = px[(i + 1) % 9]; let s = 0; for (let j = 0; j < a.length; j++) s += Math.abs(a[j] - b[j]); tot += s / a.length; }
  const motion = +(tot / 9).toFixed(2);
  check(motion >= S.minMotion, `${set}: it moves (mean frame-to-frame change >= ${S.minMotion})`, motion);
}
console.log(`\n${pass}/${pass + fail} checks passed`); process.exit(fail ? 1 : 0);
